In [392]:
import pandas as pd
from pathlib import Path

# 경로 설정
DATA_DIR = Path("data")
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"

# 원본 데이터 로드
api1 = pd.read_csv(RAW_DIR / "api_1_guide.csv")
api3 = pd.read_csv(RAW_DIR / "api_3_video.csv")

print(f"API 1: {api1.shape}")
print(f"API 3: {api3.shape}")

API 1: (8303, 35)
API 3: (1668, 32)

In [393]:
print("[API 1 컬럼]")
print(api1.columns.tolist())

print("\n[API 3 컬럼]")
print(api3.columns.tolist())

[API 1 컬럼]
['trng_mscl_nm', 'rptt_tcnt_nm', 'file_url', 'vdo_desc', 'file_sz', 'fps_cnt', 'ftns_lvl_nm', 'row_num', 'resolution', 'tool_nm', 'aggrp_nm', 'frme_no', 'ecrg_cycl_nm', 'img_file_nm', 'trng_mscl_zn_nm', 'fbctn_yr', 'nope_nm', 'trng_plc_nm', 'vdo_len', 'trng_mscl_part', 'lang', 'trng_nm', 'job_ymd', 'ftns_fctr_nm', 'trng_mscl_class', 'vdo_ttl_nm', 'snap_tm', 'trng_hr_nm', 'file_type_nm', 'file_nm', 'trng_mscl_eng_nm', 'img_file_url', 'img_file_sn', 'data_type', 'set_cnt_nm']

[API 3 컬럼]
['trng_mscl_nm', 'rptt_tcnt_nm', 'file_url', 'vdo_desc', 'file_sz', 'fps_cnt', 'row_num', 'resolution', 'tool_nm', 'aggrp_nm', 'frme_no', 'ecrg_cycl_nm', 'img_file_nm', 'trng_mscl_zn_nm', 'fbctn_yr', 'trng_plc_nm', 'vdo_len', 'trng_mscl_part', 'lang', 'trng_nm', 'job_ymd', 'trng_mscl_class', 'vdo_ttl_nm', 'snap_tm', 'trng_hr_nm', 'file_type_nm', 'file_nm', 'trng_mscl_eng_nm', 'img_file_url', 'img_file_sn', 'data_type', 'set_cnt_nm']

In [394]:
print("[API 1]")
print("전체 행:", len(api1))
print("고유 file_nm:", api1["file_nm"].nunique())
print("고유 file_url:", api1["file_url"].nunique())

print("\n[API 3]")
print("전체 행:", len(api3))
print("고유 file_nm:", api3["file_nm"].nunique())
print("고유 file_url:", api3["file_url"].nunique())

[API 1]
전체 행: 8303
고유 file_nm: 661
고유 file_url: 1

[API 3]
전체 행: 1668
고유 file_nm: 243
고유 file_url: 1

In [395]:
def check_multi_values(df, video_col="file_nm"):
    result = []

    for col in df.columns:
        if col == video_col:
            continue

        max_unique = df.groupby(video_col)[col].nunique().max()

        if max_unique > 1:
            result.append({
                "column": col,
                "max_values_per_video": max_unique
            })

    return pd.DataFrame(result).sort_values(
        "max_values_per_video",
        ascending=False
    )


print("[API 1]")
display(check_multi_values(api1))

print("[API 3]")
display(check_multi_values(api3))

[API 1]

              column  max_values_per_video
15           snap_tm                    81
3            row_num                    81
5            frme_no                    81
18       img_file_sn                    81
7        img_file_nm                    81
0       trng_mscl_nm                    26
8    trng_mscl_zn_nm                    26
17  trng_mscl_eng_nm                    26
11    trng_mscl_part                    25
14   trng_mscl_class                    22
12           trng_nm                    10
2        ftns_lvl_nm                     3
4            tool_nm                     3
13           job_ymd                     3
16        trng_hr_nm                     2
10       trng_plc_nm                     2
1       rptt_tcnt_nm                     2
9            nope_nm                     2
6       ecrg_cycl_nm                     2
19        set_cnt_nm                     2

[API 3]

              column  max_values_per_video
2            row_num                    33
16       img_file_sn                    33
4            frme_no                    33
6        img_file_nm                    33
13           snap_tm                    33
0       trng_mscl_nm                    15
15  trng_mscl_eng_nm                    15
7    trng_mscl_zn_nm                    15
10           trng_nm                    14
12   trng_mscl_class                    14
9     trng_mscl_part                    14
14        trng_hr_nm                     5
5       ecrg_cycl_nm                     4
3            tool_nm                     4
11           job_ymd                     3
17        set_cnt_nm                     3
1       rptt_tcnt_nm                     2
8        trng_plc_nm                     2

In [396]:
check_cols = [
    "tool_nm",
    "trng_plc_nm",
    "nope_nm",
    "trng_nm",
    "ftns_lvl_nm",
    "rptt_tcnt_nm",
    "set_cnt_nm",
    "trng_hr_nm",
    "ecrg_cycl_nm"
]

for col in check_cols:
    print(f"\n===== {col} =====")
    
    print("[API 1]")
    print(api1[col].dropna().unique())
    
    print("\n[API 3]")
    if col in api3.columns:
        print(api3[col].dropna().unique())
    else:
        print("해당 컬럼 없음")

===== tool_nm =====
[API 1]
['매트' '라바콘' '헬스기구' '아령' '물병' '의자' '밴드' '공' '써클링' '써클휠' '짐볼' '덤벨' '큰공' '콘'
 '줄넘기' '계단' '스텝박스' '바' '하프콘' '농구공' '배드민턴 라켓' '훌라후프' '테니스공' '계이름 판' '자전거'
 '아쿠아봉' '바벨' '원판' '보슈' '물통' '소파' '테이블' '수건' '벤치' '스텝퍼' '사다리' '폼롤러' '베개'
 '막대' '킥판' '봉' '플렉스 바' '벽' '풍선' '스카프' '줄' '지팡이' '작은공' '박스' '메디신볼']

[API 3]
['실내자전거' '트레드밀' '밴드' '킥판' '아쿠아봉' '테니스공' '자전거' '줄넘기' '헬스기구' '바벨' '원판' '덤벨'
 '봉' '물병' '짐볼' '매트' '테이블' '소파' '물병(밴드)' '수건(낮은 쿠션)' '봉(의자)' '색테이프' '의자'
 '수건' '공' '보슈' '베개' '스탭퍼' '줄사다리' '막대' '사다리' '라바콘' '헬멧' '발판' '고무줄' '풍선'
 '작은공' '지팡이' '막대기' '스카프' '허들' '색깔판']

===== trng_plc_nm =====
[API 1]
['실내' '헬스장' '실내/실외' '운동장' '실외' '수영장']

[API 3]
['헬스장' '수영장' '실내' '실외' '실내/실외' '실내/헬스장' '실내, 실외']

===== nope_nm =====
[API 1]
['1인 이상' '2인 이상' '3인 이상']

[API 3]
해당 컬럼 없음

===== trng_nm =====
[API 1]
['팔 굽혀 펴기(매트)' '누워서 뒤로 팔 굽혀 펴기' '앉아서 엉덩이 들고 이동하기' '앉아서 양팔 당기기-1'
 '엎드려 팔로 걷기' '아령 앞으로 들어올리기' '아령 뒤로 들어올리기' '의자 잡고 팔 뒤로 굽히기'
 '밴드 앞 옆으로 들어올리기' '밴드 어깨 뒤로 들어올리기' '엎드려 상체 들어올리기' '슈퍼맨 자세' '엎드려 팔 대고 버티기'
 '옆으로 팔 대고 버티기' '앉아서 다리 펴고 들어올리기' '누워서 다리 펴고 원 그리기' '팔꿈치 무릎 교차 닿기'
 '팔 구부려 등 모으기' '윗몸 말아 올리기' '머리 뒤로 깍지 끼고 상체 숙이기' '엎드려 무릎 당기기' '다리 올려 의자 넘기'
 '앉아서 밴드 당기기' '밴드로 다리 올려 버티기' '밴드 다리 올려 버티기' '밴드 앞으로 당기기' '무릎 구부려 상체 비틀기'
 '공 잡고 상체 들어올리기' '팔로 써클링 누르기' 'V자 버티기' '써클휠로 다리 끌어당기기' '옆으로 누워 다리 들어올리기'
 '엎드려 다리 들어올리기' '무릎 굽혀 엉덩이 들어올리기' '옆으로 누워 무릎 벌리기' '앉았다 일어서기(공)'
 '옆으로 다리 뻗기' '다리 앞뒤로 벌려 굽혔다 펴기' '교차 다리 굽히기' '앞으로 나가며 앉았다 일어서기'
 '앉아서 당겨 내리기-1' '뒷발 의자 올려 굽히기' '다리 옆으로 들어올리기' '앞발 의자 올려 굽히기' '앞발 들어올리기'
 '발 뒤꿈치 들어올리기' '한발 들어올리기' '밴드 한발 뒤로 들기' '의자에 앉아 다리 펴서 들어올리기' '밴드 잡고 무릎 펴기'
 '밴드 잡고 다리 옆으로 벌리기' '무릎 올려 공 닿기' '허리 비틀어 앉았다 일어서기' '제자리 뛰기' '엎드려 무릎 연속 차기'
 '왕복 달리기' '1단 줄넘기' '계단 오르기' '박스 오르내리기' '다리 모았다 벌려 뛰기' '박스 옆으로 번갈아 뛰기'
 '한발 무릎 올려차기' '무릎 굽혀 가슴 닿기' '목 스트레칭(매트)-1' '발바닥 마주대고 끌어당기기'
 '다리 굽혀(W자) 상체 뒤로 눕기' '발목 얹고 다리 잡아당기기' '다리 벌려 앞으로 상체 숙이기'
 '다리 벌려 옆으로 상체 숙이기' '한발 앞굽이 팔 위로 뻗어 가슴 내밀기' '다리 모아 상체 숙이기'
 '다리 꼬아 상체 앞으로 숙이기' '앉아서 한발 앞으로 굽히기' '앉아서 옆구리 늘려주기' '앉아 윗몸 앞으로 굽히기'
 '무릎 대고 상체 뒤로 젖히기' '엎드려 교차 발 잡아당기기' '한발 뒤로 빼고 앞으로 굽히기' '무릎 대고 옆으로 기울이기'
 '누워서 굽힌 다리 펴기' '엎드려 어깨 늘리기' '활 자세' '다리 모아 뒤로 눕기' '팔 빨리 흔들기' '잔발치기'
 '벽 잡고 빨리 뛰기' '50M 달리기' '점프해서 발바닥 치기' '점프해서 손 발끝 닿기' '제자리 멀리 뛰기'
 '대(大)자 점프 뛰기' '콘 뛰어넘기' '연속 무릎 올리기' '2단 줄넘기' '4방향 콘 찍고 달리기' '점프하며 앞으로 나가기'
 'S자 달리기' '십(十)자 달리기' '반복 옆 뛰기' '의자 잡고 반복 옆 뛰기' '양손 번갈아 공 튀기기'
 '무릎/허리 높이로 공 튀기기' '공 위로 던지고 제자리 돌아 받기' '십(十)자 드리블' '라켓으로 공치며 앞으로 가기'
 '훌라후프 하며 앞으로 가기' '공 양손으로 주고 받기' '벽 패스' '훌라후프로 공 끌고 가기' '공 던져 색깔 맞추기'
 '계이름 치기' '걷기' '달리기' '실외 자전거타기' '실내 자전거타기' '트레드밀에서 걷기' '줄넘기'
 '계단 올라갔다 내려오기' '계단 뛰어 오르기' '수영' '엉덩관절 회전하기-1' '물당기기/밀기' '옆구리 늘리기'
 '물 누르기/올리기' '발 닿기' '몸 기울이기/회전하기' '앉아서 다리 밀기' '앉아서 다리 펴기' '앉아서 다리 굽히기'
 '뒤꿈치 들기' '앉아서 다리 모으기' '앉아서 다리 벌리기' '앉아서 당겨 내리기' '앉아서 뒤로 당기기' '몸통 들어올리기'
 '앉아서 몸통 움츠리기' '앉아서 밀기' '누워서 밀기' '비스듬히 누워서 밀기' '거꾸로 누워서 밀기' '앉아서 모으기'
 '앉아서 위로 밀기' '바벨 들어 올리기' '원판 던지기' '파워클린' '바벨 앉았다 일어서기'
 '덤벨 한발 앞으로 내밀고 앉았다 일어서기' '바벨 서서 어깨 들어올리기' '턱걸이' '바벨 끌어당기기' '바벨 끌어당기기-1'
 '허리 굽혀 덤벨 들기' '매달려서 다리들기' '몸통 옆으로 굽히기' '매달려서 뒤로 팔 굽혀 펴기' '누워서 덤벨 들어올리기'
 '누워서 덤벨 모아들기' '서서 바벨 위로 밀기' '바벨 들어 팔꿈치 굽히기' '고정한 상태에서 덤벨 들고 팔꿈치 굽히기'
 '누워서 머리 위로 팔꿈치 펴기' '허기 굽혀 덤벨 위로 들기' '덤벨 옆으로 들어올리기' '손목 펴기/굽히기'
 '앉아서 팔꿈치 굽히기/펴기' '양발 서서 균형잡기' '한발 서서 균형잡기' '보슈 위에서 앉았다 일어나기' '엎드려서 균형잡기'
 '엎드려서 다리 차올리기' '서서 균형 잡으며 몸통 회전하기' '짝 운동' '서서 상체 일으키기' '앉았다 일어서기'
 '의자 앞에서 앉았다 일어서기' '한발 앞으로 내밀고 앉았다 일어서기' '의자에 한 다리 올리고 앉았다 일어서기'
 '의자에 앉아 다리 뻗어 올리기' '의자에 앉아 다리 뻗어 올리기(의자)' '의자에 앉아 다리 뻗어 올리기(매트)'
 '앉아서 엉덩관절 굽히기' '앉아서 엉덩관절 굽히기(짐볼)' '앉아서 엉덩관절 굽히기(소파)' '서서 다리 뒤로차기'
 '뒤로 당기기' '앞으로 당기기' '안으로 당기기' '바깥으로 당기기' '서서 뒤꿈치 들기(의자)'
 '서서 뒤꿈치 들기(매트/밴드)' '한발 서서 균형잡기(의자)' '방등 굽힘/발바닥 굽힘' '누워서 배가로근 수축Ⅰ'
 '누워서 배가로근 수축Ⅱ' '윗몸 올리기' '짐볼 윗몸 올리기' '소파를 이용한 윗몸 올리기' '엎드려 버티기'
 '옆으로 누워 버티기' '누워서 다리 들어올리기' '누워서 팔 다리 동시에 들어올리기' '누워서 다리 좌우로 움직이기'
 '누워서 공들고 몸 기울이기' '누워서 수직으로 다리 들어올리기' '누워서 하늘 자전거' '누워서 엉덩이 들어올리기'
 '짐볼에 다리 올리고 엉덩이 들어올리기' '네발기기 자세로 팔 다리 들기' '엎드려서 팔 다리 들기'
 '네발기기 자세에서 손바닥으로 바닥밀기' '짐볼에 엎드려서 팔 다리 들기' '짐볼에 엎드려서 몸통 젖히기(매트/짐볼)'
 '탄력밴드 어깨 가쪽 돌림' '서서 탄력밴드 당겨내리기/올리기' '짐볼에 다리 올리고 좌우로 움직이기'
 '네발기기 자세에서 다리 위로 뻗어올리기' '팔 굽혀 펴기' '팔 굽혀 펴기(매트/짐볼)' '팔 굽혀 펴기(테이블)'
 '뒤로 팔 굽혀 펴기' '허리 굽혀 팔 뒤로 들기' '물병 옆으로 들어올리기' '팔꿈치 굽히기' '목 굽힘/폄1' '목 굽힘/폄2'
 '목 굽힘/폄3' '앉았다 일어서면서 점프하기' '무릎 높여 제자리 달리기' '옆으로 펀치하기' '스텝퍼 오르내리기'
 '스텝퍼 뛰어서 오르내리기' '스텝퍼 뛰어서 넘어가기' '스텝퍼 옆으로 뛰어넘기' '스텝퍼 올라가서 점프하여 착지하기'
 '뛰어 내렸다가 바로 점프하기' '사다리 안팎 뛰기' '사다리 좌우 뛰기' '사다리 옆으로 발 옮기기' '팔 벌려 뛰기'
 '버피 운동' '점프 팔 굽혀 펴기' '다리 넓게 벌려 앉았다 일어나기' '계단 두발 뛰기' '계단 두 칸씩 두발 뛰기'
 '계단 한발 뛰기' '목 스트레칭' '등/어깨 뒤쪽 스트레칭' '가슴/어깨 앞쪽 스트레칭' '아래 팔 스트레칭' '허리 스트레칭'
 '배 스트레칭' '옆구리 스트레칭' '엉덩이 스트레칭(매트)' '엉덩이 스트레칭(매트/짐볼)' '한쪽 다리 펴고 상체 숙이기'
 '넙다리 뒤쪽 스트레칭' '넙다리 앞쪽 스트레칭' '넙다리 안쪽 스트레칭' '하지 루틴 스트레칭1' '하지 루틴 스트레칭2'
 '상지 루틴 스트레칭' '전신 루틴 스트레칭' '유산소 운동 전 동적 루틴 스트레칭' '좌식생활자를 위한 동적 루틴 스트레칭'
 '좌우' '앞뒤' '작은 공을 이용한 동적 루틴 스트레칭' '자가근막이완술 루틴 스트레칭' '빠르게 걷기(3단계)'
 '공에 엎드려서 상체 들어올리기' '물속에서 걷기' '앞 뒤 굴곡' '좌우 굴곡' '좌우 회전' '진자운동'
 '옆으로 누워서 팔 앞으로 당기기' '테이블 이용하여 팔 들어올리기' '테이블 이용하여 팔 옆으로 벌리기'
 '막대 잡고 팔 안쪽/바깥 돌림' '누워서 막대 잡고 팔 들어올리기' '누워서 막대 잡고 팔 회전하기'
 '막대 잡고 대각선으로 팔 들어올리기' '굽힘 밸런스운동' '벌림 밸런스 운동' '수건 잡고 팔 들어올리기' '등척성운동(벌림)'
 '등척성 운동(바깥돌림)' '등척성 운동(안쪽돌림)' '탄력밴드 당기면서 팔 들어올리기' '수건 이용하여 장딴지 늘리기'
 '수동적 관절가동범위 운동' '밴드 잡고 머리 위에서 팔꿈치 펴기' '고정식 트레드밀에서 걷기' '고정식 자전거 타기'
 '스텝박스 이용해 걷기' '물속에서 걷기-1' '엉덩관절 회전하기' '물 당기기/밀기' '엉덩관절 회전하기-2'
 '물 당기기/밀기-1' '옆구리 늘리기-1' '물 누르기/올리기-1' '발 닿기-1' '몸 기울이기/회전하기-1'
 '앉았다 일어서기(매트/덤벨)' '덤벨 잡고 들어올리기' '엎드려 다리 굽히기' '덤벨잡고 뒤꿈치 들기'
 '덤벨 잡고 한발 내밀어 굽혔다 펴기' '앉아서 다리 펴기-1' '바벨 잡고 한발 내밀어 굽혔다 펴기' '서서 다리 모으고 벌리기'
 '몸통 들어올리기-1' '덤벨잡고 몸통 옆으로 굽히기' '누워서 가슴 밀기' '바벨 당겨올리기' '앉아서 팔꿈치 굽히기'
 '서서 팔꿈치 펴기' '서서 덤벨 뒤로 보내기' '앉아서 어깨 위로 밀기' '앉아서 덤벨 위로 밀기' '앉아서 손목 굽히기'
 '앉아서 바벨로 손목 굽히기' '짐볼 이용해 앉았다 일어서기' '공 앞으로 보내고 짐볼 이용해 앉았다 일어나기'
 '공 잡고 들어올리기' '물병 들고 한발 앞으로 내밀고 앉았다 일어서기' '의자 잡고 한발 앞으로 내밀고 앉았다 일어서기'
 '밴드 걸고 엎드려 다리 구부리기' '공 끼우고 엎드려 다리 올리기' '의자에 밴드 걸고 서서 다리 뒤로 당기기'
 '밴드 걸고 누워 다리 들어올리기' '의자에 앉아 밴드 다리 들어올리기' '봉 잡고 앉았다 일어서기' '의자 잡고 앉았다 일어나기'
 '밴드 걸고 앉아 발등 굽힘' '의자에 앉아 발바닥 굽힘' '의자 잡고 서서 발바닥 굽힘' '밴드 걸고 옆으로 누워 다리 올리기'
 '발목에 밴드 감고 양 옆으로 벌리기' '의자에 앉아 다리로 짐볼 쥐기' '밴드 잡고 누워서 다리 밀기'
 '밴드 잡고 앉아서 다리 밀기' '엎드려 뒤로 다리 올리기' '밴드를 이용해 엎드려 뒤로 다리 올리기' '몸통 들어올리기-2'
 '물병 양팔 들어올리기' '밴드로 양팔 들어올리기' '물병 머리 뒤로 들어올리기' '밴드 머리 뒤로 들어올리기'
 '공 머리 뒤로 들어올리기' '플렉스 바 비틀기' '벽에서 팔 굽혀 펴기' '바닥에 무릎 대고 팔 굽혀 펴기'
 '밴드 잡고 벽에서 팔 굽혀 펴기' '누워서 공 뒤로 내리고 당기기' '짐볼 들고 양옆으로 돌리기' '의자에 앉아 볼 돌리기'
 '짐볼 위에 앉아 밴드 양옆으로 당기기' '짐볼에서 몸통 돌리기' '무릎 대고 짐볼에서 몸통 돌리기'
 '의자에 앉아 공으로 몸통 돌리기' '짐볼에서 엉덩이 돌리기' '짐볼에서 윗몸 일으키기' '다리로 짐볼 들어올리기'
 '의자에 앉아 등 굽혔다 펴기' '엎드려 양팔 및 다리 들어올리기' '앉아서 밴드 잡고 몸통 돌리기'
 '앉아서 공 잡고 몸통 돌리기' '앉아서 짐볼 잡고 몸통 돌리기' '밴드 잡고 몸통 옆으로 굽히기' '누워서 전신 뻗기'
 '깍지 끼고 상체 숙이기' '목 스트레칭(매트)' '등/어깨 스트레칭' '어깨 뒤쪽 스트레칭' '아래 팔 스트레칭(매트)'
 '엉덩이 스트레칭1' '엉덩이 스트레칭2' '넙다리 앞쪽 스트레칭-1' '넙다리 안쪽 스트레칭-1' '허리 스트레칭-1'
 '배 스트레칭-2' '옆구리 스트레칭(매트)' '양팔 벌려 전신 비틀기' '목 돌림 스트레칭' '회전근개 스트레칭'
 '어깨 스트레칭' '어깨 양 옆으로 돌리기' '골반 스트레칭1' '골반 스트레칭1-1' '몸통 앞으로 굽혀 걷기'
 '전신 틀어 손뼉 마주치기' '몸통 비틀기' '가슴/어깨 스트레칭' '회전근개 스트레칭1' '회전근개 스트레칭2'
 '몸통 비틀기-1' '등 대고 대퇴이두근 스트레칭' '마주 앉아 대퇴이두근 스트레칭1' '마주 앉아 대퇴이두근 스트레칭2'
 '고관절 스트레칭' '대퇴이두근 스트레칭1' '대퇴이두근 스트레칭2' '대퇴사두근 스트레칭' '엉덩이 스트레칭2-1'
 '종아리 스트레칭' '의자에 앉아 몸통 비틀기' '몸통 옆으로 굽히기-1' '목 스트레칭(의자)' '가슴 스트레칭'
 '팔꿈치 맞닿아 원그리기' '등/어깨뒤쪽 스트레칭' '옆구리 스트레칭(의자)' '옆구리 스트레칭(의자)-1' '몸 앞으로 굽히기'
 '내전근 스트레칭' '엉덩이 스트레칭(의자)' '대퇴사두근 스트레칭-1' '발가락 폄근 스트레칭' '비복근 스트레칭'
 '짐볼 앞으로 밀기' '짐볼 양옆으로 굴리기' '짐볼 옆에 두고 어깨 누르기' '짐볼 양팔로 밀기'
 '무릎 아래에서 양옆으로 굴리기' '복부 스트레칭' '등 스트레칭' '엉덩이 스트레칭(매트/짐볼)-1'
 '골반 스트레칭1(매트/짐볼)' '골반 스트레칭2' '척추 스트레칭' '어깨 올리기' '어깨 스트레칭(폼롤러)'
 '팔 교대로 올리기' '옆으로 누워 가슴 열기' '가슴 스트레칭(폼롤러)' '옆으로 누워 폼롤러 굴려주기' '폼롤러 앞으로 굴리기'
 '폼롤러 밀며 몸 앞으로 숙이기' '양발 나란히 서기' '좌우 찍기' '한발 들기' '의자 잡고 한발 들기'
 '의자 잡고 측면으로 한발 들기' '의자 잡고 후방으로 한발 뻗어들기' '의자 잡고 후방으로 무릎 굽혀 들기'
 '의자잡고 전방으로 무릎 굽혀 들기' '베개 밟고 교차 서기' '베개 밟고 서기' '베개 밟고 대각방향으로 서기'
 '베개 밟고 측면으로 양팔 들기' '베개 밟고 위로 양팔 들기' '탄력밴드 전방으로 당기기' '탄력밴드 후방으로 당기기'
 '탄력밴드 측면으로 당기기' '탄력밴드 후방 측면으로 당기기' '탄력밴드 무릎으로 당기기' '균형걷기' '짐볼 앉아 양손 가슴교차'
 '짐볼 앉아 상체 숙이기' '짐볼 앉아 뒤꿈치 들기' '짐볼 앉아 앞꿈치 들기' '짐볼 앉아 한손 측면으로 들기'
 '짐볼 앉아 양손 측면으로 들기' '짐볼 앉아 한발 들기' '짐볼 앉아 양손 대각방향으로 들기' '짐볼 앉아 한발 내딛기'
 '짐볼 앉아 몸통 돌리기' '좌/우로 선 넘기' '상하로 움직이며 실시하기' '앞/뒤로 선 넘기' '한발 따라가기'
 '대각방향으로 넘기' '두발 모아 점프하기' '발바닥 치기' '머리 위로 공 넘기기' '다리 사이로 공 건네기' '풍선 튕기기'
 '성화봉송' '스카프 저글링' '스카프 라인' '하프콘 투호' '줄 따라 걷기' '발로 공주고 받기' '방향전환하며 걷기'
 '8자 걷기' '사다리 걷기' '발가락으로 수건 말기' '의자 이용하기' '의자 손 안 짚고 일어났다 앉기' '제기차기'
 '의자 앉아 공 밀기' '누워서 가슴 밀기-1' '엎드려 다리 굽히기-1' '서서 다리 모으고 벌리기-1'
 '앉아서 뒤로 당기기-1' '앉아서 몸통 움츠리기-1' '앉아서 팔꿈치 굽히기-1' '서서 팔꿈치 펴기-1'
 '고정식 트레드밀 걷기' '옆구리 스트레칭(매트)-1' '배 스트레칭-3' '넙다리 안쪽 스트레칭-2' '엉덩이 스트레칭1-1'
 '엉덩이 스트레칭2-3' '허리 스트레칭-2' '짐볼 앞으로 밀기(짐볼)' '짐볼 양옆으로 굴리기(짐볼)' '등 스트레칭-1'
 '짐볼 무릎 아래에서 양옆으로 굴리기' '엉덩이 스트레칭(짐볼)' '골반 스트레칭1(짐볼)' '의자에 앉아 등 굽혔다 펴기-1'
 '짐볼에서 몸통 돌리기-1' '짐볼에서 엉덩이 돌리기(짐볼)' '짐볼에서 윗몸 일으키기(짐볼)'
 '앉아서 밴드 잡고 몸통 돌리기(밴드)' '옆구리 스트레칭(매트)-2' '엉덩이 스트레칭2-4' '넙다리 안쪽 스트레칭-3'
 '허리 스트레칭-3' '배 스트레칭-4' '앉아서 다리 밀기-1' '앉아서 몸통 움츠리기-2' '앉아서 가슴 모으기'
 '앉아서 어깨 위로 밀기-1' '짐볼 이용해 앉았다 일어서기-1' '짐볼에서 엉덩이 돌리기(짐볼)-1'
 '물병 들고 한발 앞으로 내밀고 앉았다 일어서기-1' '밴드 걸고 엎드려 다리 구부리기(밴드)'
 '밴드 걸고 옆으로 누워 다리 올리기(밴드)' '밴드 걸고 앉아 발등 굽힘(밴드)' '스텝박스 이용해 걷기-1'
 '엉덩이 스트레칭1-2' '엉덩이 스트레칭2-5' '넙다리 앞쪽 스트레칭-3' '옆구리 스트레칭(매트)-3'
 '넙다리 안쪽 스트레칭-4' '밴드 걸고 누워 다리 들어올리기(밴드)' '봉 잡고 앉았다 일어서기-1'
 '물병 들고 한발 앞으로 내밀고 앉았다 일어서기-2' '밴드 걸고 엎드려 다리 구부리기(밴드)-1'
 '밴드 잡고 누워서 다리 밀기(밴드)' '앉았다 일어서기(덤벨)' '덤벨 잡고 한발 내밀어 굽혔다 펴기-1'
 '앉아서 다리 밀기-2' '앉아서 다리 펴기-2' '엎드려 다리 굽히기-2' '서서 다리 모으고 벌리기-2'
 '앉아서 뒤로 당기기-2' '누워서 가슴 밀기-2' '고정식 자전거 타기(자전거)' '몸통 비틀기-2' '가슴/어깨 스트레칭-1'
 '회전근개 스트레칭1-1' '어깨 스트레칭-1' '엉덩이 스트레칭' '고관절 스트레칭-1' '마주 앉아 대퇴이두근 스트레칭2-1'
 '짐볼을 이용해 앉았다 일어서기' '공 잡고 들어올리기-1' '누워서 공 뒤로 내리고 당기기(공)'
 '짐볼 들고 양옆으로 돌리기-1' '짐볼에서 엉덩이 돌리기(짐볼)-2' '짐볼에서 윗몸 일으키기(짐볼)-1' '물 당기기/밀기-3'
 '엉덩관절 회전하기-3' '발 닿기-3' '옆구리 늘리기-3' '물 누르기/올리기-3' '몸 기울이기/회전하기-3'
 '스카프 라인-1' '제기차기-1' '의자 앉아 공 밀기-1' '풍선 튕기기-1' '등/어깨 뒤쪽 스트레칭-1'
 '엉덩이 스트레칭(의자)-1' '대퇴사두근 스트레칭-3' '발가락 폄근 스트레칭-1' '비복근 스트레칭-1'
 '밴드 머리 뒤로 들어올리기(밴드)' '밴드 잡고 누워서 다리 밀기(밴드)-1' '밴드 걸고 엎드려 다리 구부리기(밴드)-2'
 '밴드 걸고 옆으로 누워 다리 올리기(밴드)-2' '몸통 들어올리기-3' '벽에서 팔 굽혀 펴기-1' '물병 양팔 들어올리기-1'
 '밴드 걸고 앉아 발등 굽힘(밴드)-1' '의자 잡고 한발 들기(밴드)' '의자 잡고 측면으로 한발 들기(밴드)'
 '의자 잡고 후방으로 한발 뻗어들기(밴드)' '의자 잡고 후방으로 무릎 굽혀 들기(밴드)' '의자 잡고 전방으로 무릎 굽혀 들기'
 '탄력밴드 전방으로 당기기(밴드/봉)' '탄력밴드 후방으로 당기기(밴드/봉)' '탄력밴드 측면으로 당기기(밴드/봉)'
 '탄력밴드 후방 측면으로 당기기(밴드/봉)' '턴력밴드 무릎으로 당기기' '짐볼 앉아 양손 가슴교차(짐볼)'
 '짐볼 앉아 몸통 돌리기(짐볼)' '짐볼 앉아 상체 숙이기(짐볼)' '짐볼 앉아 뒤꿈치 들기(짐볼)'
 '짐볼 앉아 앞꿈치 들기(짐볼)' '짐볼 앉아 한손 측면으로 들기(짐볼)' '짐볼 앉아 양손 측면으로 들기(짐볼)'
 '짐볼 앉아 양손 대각방향으로 들기(짐볼)' '짐볼 앉아 한발 내딛기(짐볼)' '짐볼 앉아 한발 들기(짐볼)' '사다리 걷기-1'
 '양발 나란히 서기(매트)' '좌우 찍기(매트)' '한발 들기(매트)' '척추 스트레칭-1' '어깨 올리기-1'
 '폼롤러 밀며 몸 앞으로 숙이기-1' '옆으로 누워 가슴 열기-1' '옆으로 누워 폼롤러 굴려주기-1'
 '옆구리 스트레칭(의자)-2' '목 스트레칭(의자)-1' '팔꿈치 맞닿아 원그리기-1' '가슴 스트레칭(의자)-1'
 '엉덩이 스트레칭(의자)-2' '비복근 스트레칭-2' '공 잡고 들어올리기-2' '짐볼 이용해 앉았다 일어서기-2'
 '누워서 공 뒤로 내리고 당기기(공)-1' '짐볼에서 몸통 돌리기-3' '짐볼에서 윗몸 일으키기(짐볼)-2'
 '다리로 짐볼 들어올리기-1' '의자 잡고 앉았다 일어나기(의자)' '의자에 앉아 공 다리 들어올리기-1'
 '의자에 앉아 등 굽혔다 펴기-2' '앉아서 다리 밀기-3' '앉아서 다리 펴기-3' '엎드려 다리 굽히기-3'
 '누워서 가슴 밀기-3' '앉아서 당겨 내리기-2' '앉아서 팔꿈치 굽히기-2' '서서 팔꿈치 펴기-2'
 '앉아서 몸통 움츠리기-3' '발 닿기-4' '물 당기기/밀기-4' '옆구리 늘리기-4' '물 누르기/올리기-4'
 '몸 기울이기/회전하기-4' '빠른 발 뛰기' '엇박자 뛰기' '양발 모아 좌우 뛰기' '한발 연속 뛰기' '양발 모았다 벌려뛰기'
 '빠른 발 안팎 뛰기' '한발 앞뒤 교차 뛰기' '양발 교차 뛰기' '크게 다리벌려 교차 뛰기' '한발 끌어당기기'
 '뒷발 교차 뛰기' '양발 연속 뛰기' '사이드 스텝' 'W 스텝' '앞뒤 지그재그 뛰기' '무릎 들어 연속 뛰기'
 '전후 교차 뛰기' '사이드 지그재그 뛰기' '순간반응 콘 찍기' '순간반응 콘 찍기2' '뒤꿈치 높이들어 뛰기'
 '무릎 높이들어 뛰기' '점프하며 뛰기' '빠르게 무릎들어 뛰기' '옆으로 굽히기' '뛰어 밀기'
 '앉았다 일어서기(매트/바벨)-1' '제자리 멀리 뛰기-1' '앞굽이 뛰기' '앉았다 일어나며 점프하기' '양팔 벌려 높이 뛰기'
 '앞차기하며 뛰기' '사이드 한발 뛰기' '다리 뻗어 점프하기' '양발 점프 착지하기(박스)' '점프 후 버티기(박스)'
 '사이드 스텝 점프하기(박스)' '빠르게 앞무릎 올리기(박스)' '연속 하향 점프하기(박스)' '좌우 양발모아 점프하기(박스)'
 '한발로 점프하기(박스)' '연속 상향 점프하기(박스)' '좌우 이동하며 팔 굽혀 펴기' '팔 굽혀 펴기 후 점프하기(박스)'
 '조깅' '자전거 타기' '머리 위로 볼 돌리기' '볼 잡고 몸통 기울이기' '허리 감아 볼 돌리기'
 '메디신 볼 잡고 팔 굽혀 펴기' '볼 튕기면서 스쿼트' '종아리 사이 감아 돌리기' '메디신 볼 잡고 런지하며 상체비틀기'
 '볼 잡고 점프하기' '허리 비틀어 볼 주고받기' '양발 교차 올리기(짐볼)' '누워 무릎 교차 올리기'
 '짐볼 전완대고 버티기(짐볼)' '짐볼 배에 대고 버티기(짐볼)' '짐볼 윗몸 일으키기(짐볼)' '다리 교대로 들어올리기'
 '양손 모아 균형잡기' '백 슬라이드' '바로서서 상체 숙이기' '누워 다리 들어올리기' '의자에 앉아 물병 들고 몸통 돌리기'
 '발에 밴드걸고 윗몸 일으키기-1' 'V자 싸이클' '전완대고 버티기' '윗몸 일으키기' '손 뻗어 윗몸 일으키기(매트)'
 '누워 무릎 기울기' '다리 뻗어 올리기' '앞굽이 앉았다 일어서기' '연속 사이드 스쿼트' '엎드려 팔 다리 교차올리기'
 '팔 다리 교차 버티기' '발 바꿔 뛰기' '버피 테스트' '크런치 싸이클' '누워서 팔 밀기' '앉아서 양팔 당기기'
 '다리 넓게 벌려 앉았다 일어서기' '누워서 다리 굽히기' '앉았다 일어서기(매트/바벨)' '팔꿈치 고정 후 벌리기(밴드)'
 '양팔 크게 벌리기(밴드)' '뒤로 팔 뻗기' '앉아서 다리 올리기' '앉아서 무릎 굽히기' '한발 들어올리기(밴드)'
 '한발 끌어당기기(밴드)' '옆으로 굽히기(밴드)' '발에 밴드걸고 윗몸 일으키기' '상체 감아올리기' '다리 감아올리기'
 '한발 뒤로 들어올리기(밴드)' '팔 들어 올리며 런지' '런지하며 상체 비틀기' '앉았다 일어서며 팔 들어올리기(밴드)'
 '고양이 자세' '복식 호흡' '반달 자세' '물고기 자세' '누워 한발 원 그리기' '엎드려 한발 원 그리기' '발목 돌리기'
 '발 끝 당기기' '나비 자세' '왜가리 자세' '아기 자세' '휴식 자세' '결가부좌' '앉은 산 자세' '모관운동'
 '다리 자세' '소머리 자세' '전사 자세' '회전 초승달 자세' '전갈 자세' '합장하여 앞으로 숙이기' '스타 투 니 풀'
 '측면 팔대고 버티기' '레그 스윙' '시소우' '나무 자세' '겨드랑이 늘리기' '팔 당기기' '어깨 누르기'
 '나란히 서서 손잡고 끌어당기기' '가슴/어깨 펴기' '마주보고 상체 좌우 비틀기' '웅크리고 앉아 손잡고 상체 숙이기'
 '상체 앞으로 숙이기' '한쪽 다리펴고 상체 숙이기' '앉아서 상체 앞/옆으로 기울기' '엉덩이 늘리기' '마주보고 종아리 펴기'
 '발등 동시에 늘리기' '목 돌리기' '팔꿈치 원 그리기' '무릎 들어올리기' '다리들어 옆으로 올리기' '무릎 굽혀 원 그리기'
 '빠르게 무릎 올려 찍기' '전진 점프하며 발바닥 찍기' '전진 점프하며 발 뒤꿈치 찍기' '짐볼 윗몸 일으키기'
 '허리숙여 양팔 돌리기' '옆으로 팔 벌리며 점프하기' '팔 돌리며 점프하기' '네발 걷기' '전신 비틀며 전진하기'
 '다리 들어올리기' '팔꿈치 머리 뒤로 젖히기-1' '자세낮춰 이동하기' '서서 한팔 들어 오른쪽/왼쪽 뻗기-1'
 '다리벌려 풍차돌기' '한발 들어 좌우 돌리기' '목 당기기' '깍지끼고 목 들어올리기' '팔꿈치 머리 뒤로 젖히기'
 '의자에 앉아 가슴 뒤로 젖히기' '의자에 앉아 몸통비틀기' '몸통 스트레칭' '다리굽혀 허리 비틀기'
 '의자에 앉아 가슴/몸통 말아주기' '서서 한팔 들어 오른쪽/왼쪽 뻗기' '옆구리 스트레칭(매트)-4' '척추 들어올리기'
 '엎드려 상체 들어올리기-1' '의자에 앉아 옆구리 숙이기' '무릎 당겨올리기' '다리뻗어 상체 숙이기' '무릎 당겨 다리 올리기'
 '다리모아 무릎 누르기' '누워 발목 당겨주기' '양발 교차하여 서서 몸통 숙이기' '서서 발목 누르기' '서서 발목 뒤로 당기기'
 '양발 벌려 무릎 밀어내기' '온 몸 뻗어주기' '팔꿈치 원 그리기-1' '목 돌리기-1' '다리 들어 옆으로 올리기'
 '무릎 들어올리기-1' '빠르게 무릎 올려 찍기-1' '허리 숙여 양팔 돌리기' '팔 돌리며 점프하기-1'
 '전신 비틀며 전진하기-1' '다리 들어올리기-1' '팔 굽혀 펴기-1' '바로서서 상체 숙이기-1' '손 뻗어 윗몸 일으키기'
 'V자 싸이클-1' '누워 무릎 기울기-1' '앉았다 일어서기-1' '앞굽이 앉았다 일어서기-1' '연속 사이드 스쿼트-1'
 '머리 위로 볼 돌리기-1' '허리 감아 볼 돌리기-1' '메디신 볼 잡고 팔 굽혀 펴기-1' '볼 튕기면서 스쿼트-1'
 '종아리 사이 감아 돌리기-1' '메디신 볼 잡고 런지하며 상체비틀기-1' '볼 잡고 점프하기-1' '허리 비틀어 볼 주고받기-1'
 '양발 점프 착지하기' '점프 후 버티기' '빠르게 앞무릎 올리기' '앉았다 일어서며 팔 들어올리기' '사이드 스텝 점프하기'
 '좌우 양발모아 점프하기' '한발로 점프하기' '연속 하향 점프하기' '팔 굽혀 펴기 후 점프하기' '연속 상향 점프하기'
 '양손 모아 균형 잡기' '빠른 발 뛰기(스텝레더)' '엇박자 뛰기(스텝레더)' '양발 모아 좌우 뛰기(스텝레더)'
 '양발 모았다 벌려뛰기(스텝레더)' '한발 연속 뛰기(스텝레더)' '한발 앞뒤 교차 뛰기(스텝레더)' '양발 교차 뛰기(스텝레더)'
 '크게 다리벌려 교차 뛰기(스텝레더)' '뒷발 교차 뛰기-1' '몸통비틀기' '누워서 팔 밀기-1' '앉아서 가슴 모으기-1'
 '앉아서 가슴 모으기-2' '척추 들어올리기-1' '팔꿈치 고정 후 벌리기' '양팔 크게 벌리기' '한발 뒤로 들어올리기'
 '런지하며 상체 비틀기-1' '목 당기기-1' '양발 벌려 무릎 밀어내기-1' '엎드려 상체 들어올리기-2'
 '의자에 앉아 가슴 뒤로 젖히기-1' '양발 교차하여 서서 몸통 숙이기-1' '서서 발목 뒤로 당기기-1' '양발 교차 올리기'
 '누워 무릎 교차 올리기-1' '짐볼 전완대고 버티기' '짐볼 배에 대고 버티기' '다리 교대로 들어올리기-2'
 '백 슬라이드(짐볼/매트)' '겨드랑이 늘리기-1' '가슴/어깨 펴기-1' '팔 당기기-1' '마주보고 종아리 펴기-1'
 '마주보고 상체 좌우 비틀기-1' '웅크리고 앉아 손잡고 상체 숙이기-1' '나란히 서서 손잡고 끌어당기기-1'
 '양발 연속 뛰기-1' 'Banded Jumping Jack' '앞뒤 지그재그 뛰기-1' '무릎 들어 연속 뛰기-1'
 '사이드 지그재그 뛰기-1' 'W 스텝-1' '전후 교차 뛰기-1' '순간반응 콘 찍기-1' 'Glute Bridge'
 '순간반응 콘 찍기2-1' 'Lying Hip Abduction' 'Clamshell' 'Side Walk and Squat'
 'Deadlift' 'Knee Up' 'Overhead Raise' 'Y Raise' 'Superman Kick']

[API 3]
['실내 자전거타기' '트레드밀에서 걷기' '손목/발목 돌리기' '무릎 돌리기' '허리 돌리기' '어깨 돌리기' '목 돌리기'
 '앉았다 일어서기(수영기초)' '양팔 벌려 뛰기' '물에 뜨기' '호흡하기' '발 동작(자유형)' '팔 동작(자유형)'
 '어깨 안쪽 돌림' '배영자세와 물에 뜨기' '발 동작(배영)' '어깨 롤링' '팔 동작(배영)' '발 동작(평영)'
 '팔 동작(평영)' '발 동작(접영)' '팔 동작(접영)' '엉덩관절 회전하기' '물당기기/밀기' '옆구리 늘리기'
 '물 누르기/올리기' '발 닿기' '몸 기울이기/회전하기' '걷기' '빠르게 걷기' '가슴' '달리기' '전완(내측)'
 '실외 자전거타기' '양발 넘기기' '한발 넘기기' '계단 올라갔다 내려오기' '목 상부' '계단 뛰어 오르기'
 '허벅지(햄스트링)' '종아리(기본)' '정강이' '스텝박스 오르내리기' '엎드려 양발 교차로 당기기' '앉아서 다리 밀기'
 '앉아서 다리 펴기' '앉아서 다리 굽히기' '뒤꿈치 들기' '앉아서 다리 모으기' '앉아서 다리 벌리기' '허리'
 '앉아서 당겨 내리기' '앉아서 뒤로 당기기' '몸통 들어올리기' '앉아서 몸통 움츠리기' '앉아서 밀기' '누워서 밀기'
 '비스듬히 누워서 밀기' '거꾸로 누워서 밀기' '앉아서 모으기' '앉아서 위로 밀기' '엎드려서 다리 굽히기'
 '서서 다리 모으고 벌리기' '앉아서 팔꿈치 굽히기' '서서 팔꿈치 펴기' '바벨 들어올리기' '원판 던지기' '파워클린'
 '앉았다 일어서기(바벨)' '한발 앞으로 내밀고 앉았다 일어서기(덤벨)' '서서 어깨 들어올리기' '턱걸이' '바벨 끌어당기기'
 '허리 굽혀 덤벨 들기' '목 외측' '매달려서 다리 들기' '몸통 옆으로 굽히기' '매달려서 뒤로 팔 굽혀 펴기'
 '누워서 덤벨 들어올리기' '누워서 덤벨 모아들기' '서서 바벨 위로 밀기' '바벨 들어 팔꿈치 굽히기'
 '고정한 상태에서 덤벨 들고 팔꿈치 굽히기' '누워서 머리위로 팔꿈치 펴기' '허리 굽혀 덤벨 뒤로 들기'
 '덤벨 옆으로 들어올리기' '손목 펴기/굽히기' '서서 상체 일으키기' '앉았다 일어서기' '한발 앞으로 내밀고 앉았다 일어서기'
 '누워서 배가로근 수축1' '누워서 배가로근 수축2' '엎드려 버티기' '옆으로 누워 버티기' '누워서 다리 들어올리기'
 '누워서 팔 다리 동시에 들어올리기' '윗몸 올리기' '엎드려 양팔 올리기' '누워서 하늘 자전거' '누워서 엉덩이 들어올리기'
 '네발기기 자세에서 팔 다리 들기' '엎드려서 팔 다리 들기' '네발기기 자세에서 손바닥으로 바닥밀기'
 '네발기기 자세에서 다리 위로 뻗어올리기' '팔 굽혀 펴기' '누워서 팔 다리 교차 뻗기' '뒤로 팔 굽혀 펴기'
 '허리 굽혀 팔 뒤로 들기' '물병 옆으로 들어올리기' '팔꿈치 굽히기' '목 굽힘/폄1' '목 굽힘/폄2' '목 굽힘/폄3'
 '벽에서 팔 굽혀 펴기' '봉잡고 앉았다 일어나기' '서서 상체 앞으로 숙였다 세우기' '양발 나란히 서기' '좌/우 찍기'
 '한발 들기' '균형 걷기' '발교차 걷기' '의자 앞에서 앉았다 일어서기' '의자에 한 다리 올리고 앉았다 일어서기'
 '의자에 앉아 다리 뻗어 올리기' '앉아서 엉덩관절 굽히기' '서서 다리 뒤로 차기' '서서 뒤꿈치 들기' '한발 서서 균형잡기'
 '소파를 이용한 윗몸 올리기' '의자에서 뒤로 팔 굽혀 펴기' '의자에 앉아 등 굽혔다 펴기' '의자잡고 한발 들기'
 '의자잡고 후방으로 한발 뻗어 들기' '의자잡고 후방으로 무릎 굽혀 들기' '의자잡고 전방으로 무릎 굽혀 들기' '앞으로 당기기'
 '뒤로 당기기' '안으로 당기기' '바깥으로 당기기' '발바닥 굽힘' '발등 굽힘' '가쪽번짐' '탄력밴드 어깨 가쪽 돌림'
 '당겨내리기' '당겨올리기' '밴드 걸고 엎드려서 다리 구부리기' '전완(외측)' '밴드 걸고 누워서 다리 들어올리기'
 '의자에 앉아 공 다리 들어올리기' '밴드 걸고 옆으로 누워 다리 올리기' '발목에 밴드 감고 양옆으로 벌리기'
 '밴드 잡고 누워서 다리 밀기' '밴드 머리 뒤로 들어올리기' '탄력밴드 전방으로 당기기' '탄력밴드 후방으로 당기기'
 '탄력밴드 측면으로 당기기' '탄력밴드 후방 측면으로 당기기' '탄력밴드 무릎으로 당기기' '짐볼 윗몸 올리기'
 '짐볼에 다리 올리고 엉덩이 들어올리기' '짐볼에 엎드려서 팔 다리 들기' '짐볼에 엎드려서 몸통 젖히기'
 '짐볼에 다리 올리고 좌/우로 움직이기' '의자에 앉아 다리로 짐볼 쥐기' '짐볼 들고 양옆으로 돌리기'
 '볼 위에 앉아 밴드 양옆으로 당기기' '의자에 앉아 밴드 양옆으로 늘이기' '짐볼에서 몸통 돌리기' '짐볼에서 윗몸 일으키기'
 '의자에 앉아 다리 들어 올리기' '다리로 짐볼 들어올리기' '짐볼 앉기 루틴 프로그램' '누워서 다리 좌/우로 움직이기'
 '누워서 공들고 몸 기울이기' '누워서 수직으로 다리 들어올리' '공 잡고 들어올리기' '밴드 잡고 들어올리기'
 '짐볼 잡고 들어올리기' '누워서 공 뒤로 내리고 당기기' '누워서 봉 뒤로 내리고 당기기' '누워서 짐볼 뒤로 내리고 당기기'
 '의자에 앉아 볼 돌리기' '앉아서 팔꿈치 굽히기/펴기' '서서 균형잡기' '엎드려서 균형잡기' '윗몸 말아 올리기'
 '엎드려서 다리 차올리기' '서서 균형잡으며 몸통 회전하기' '짝 운동' '베개 밟고 서기 루틴 프로그램'
 '앉았다 일어서면서 점프하기' '무릎 높여 제자리 달리기' '옆으로 펀치하기' '팔 벌려 뛰기' '버피 운동'
 '점프 팔 굽혀 펴기' '계단 두발 뛰기' '계단 두 칸씩 두발 뛰기' '계단 한발 뛰기' '양팔 대각선으로 올리기'
 '스텝퍼 뛰어서 오르내리기' '누워서 다리 곧게 펴서 올리기' '스텝퍼 옆으로 뛰어넘기' '스텝퍼 올라가서 점프하여 착지하기'
 '뛰어 내렸다가 바로 점프하기' '사다리 안팎 뛰기' '사다리 좌/우 뛰기' '사다리 옆으로 발 옮기기'
 '공에 엎드려서 상체 들어올리기' '물속에서 걷기' '앞 뒤 굴곡(목 앞 뒤 굴곡)' '좌/우 굴곡(목 좌/우 굴곡)'
 '좌/우 회전(목 좌/우 회전)' '진자 운동' '옆으로 누워서 팔 앞으로 당기기' '테이블 이용하여 팔 들어올리기'
 '테이블 이용하여 팔 옆으로 벌리기' '막대 잡고 팔 안쪽 바깥 돌림' '누워서 막대 잡고 팔 들어올리기'
 '누워서 막대 잡고 팔 회전하기' '막대 잡고 대각선으로 팔 들어올리기' '수건 잡고 팔 들어올리기' '벌림' '바깥돌림'
 '안쪽 돌림' '탄력밴드 당기면서 팔 들어올리기' '수건 이용하여 장딴지 늘리기' '수동적 관절가동범위 운동'
 '밴드 잡고 머리 위에서 팔꿈치 펴기' '셋 하면 달리기' '개구리 점프해요' '한 발 뛰기' '두 발 뛰기' '뛰어 넘기'
 '미끄러지기' '말처럼 달리기' '번갈아 뛰기' '손가락 숫자세기' '가위 바위 보해요' '뽁뽁이를 눌러요(손가락)'
 '엉긍엉금 기어요(준비)' '엉긍엉금 기어요' '영차영차 올라요' '걷기, 제자리 걷기' '손가락 박수치기' '사이드 스텝'
 '쌀 보리 해봐요' '높이 멀리 뛰기' '팔 스트레칭' '어깨 스트레칭' '다리 스트레칭(준비)' '허수아비가 되어요(준비)'
 '허수아비가 되어요(발등)' '허수아비가 되어요(무릎)' '허수아비가 되어요(무릎 앞)' '중심을 잡아요' '끌어요 당겨요(준비)'
 '끌어요 당겨요' '빌리보를 밀어요' '윗몸 말며 공 전달하기(준비)' '윗몸 말며 공 전달하기' '팔 펴고 박수치기'
 '머리 어깨 무릎 발 해요' '뽁뽁이를 밟아요(발가락)' '구르기를 해요' '딩링링을 끼워요' '고무줄 놀이' '공 굴리기'
 '공 던지기' '공 받기' '공 튀기기' '공 치기(손)' '공 차기' '공 멈추기(발)' '공 치기(막대기/배트)' '꼬리잡기'
 '점프하기' '줄넘기' '공 옮기기' '뒤로 눕기' '발차기' '손바닥 치기' '물건 잡기' '공 붙이기' '밸런스 보드에 서기'
 '공 올리기' '평균대 걷기' '교구 위 걷기' '공받기' '공던지기' '장애물 걷기' '집게로 집기' '낚시하기'
 '허리굽혀 걷기' '팔 다리 흔들기' '팔 흔들기' '중심잡기' '제자리 돌기(보조)' '앉아서 돌기' '서서 돌기'
 '장애물 위로 걷기' '점프' '한 발 점프' '말처럼 점프' '한 발 교차 점프' '공 던지기(오버헤드)'
 '공 던지기(언더핸드)' '풍선치기(라켓-언더)' '풍선치기(라켓-오버)' '풍선치기(라켓)' '발로 공 멈추기' '막대로 공치기'
 '밴드 당기기' '새처럼 날아요-팔벌린자세' '새처럼 날아요-차렷자세' '펀치스텝(왼손)' '펀치스텝(오른손)' '펀치스텝(보조)'
 '총총총 뛰어요(준비동작)' '점프펀치' '점프펀치(보조)' '빵야 빵야를 해요' '굽히기를 해요' '비틀기를 해요'
 '흔들기를 해요' '돌기를 해요' '거꾸로 균형을 잡아요' '네 발로 걸어요' '엎드려 암터치' '엉금엉금 기어요'
 '브릿지 만들기' '브릿지 만들기(준비)' '윗몸 말아 올리기(준비)' '목 스트레칭' '허리 스트레칭' '윗몸 스트레칭'
 '다리 스트레칭' '다리벌려 앞으로 굽히기(준비)' '다리벌려 앞으로 굽히기(꽃받침자세)'
 '다리벌려 앞으로 굽히기(다리벌려 엎드리기)' '다리모아 앞으로 굽히기(준비자세)' '다리모아 앞으로 굽히기' '크로스오버'
 '파이크 푸시업' '점핑 잭' '제자리 걸으면서 손목 돌리기' '다리 어깨너비로 벌려 팔꿈치 돌리기' '다이나믹 스트레칭'
 '마운틴 클라이머' '버피테스트/푸시업' '브이업' '힌두 푸시업' '숨쉬기' '깍지끼고 천장보기' '깍지끼고 옆구리 늘리기'
 '가슴펴고 천장보기' '앞굽이 자세' '다리벌려 어깨 내밀기' '플랭크 잭' '스쿼트 점프' '와이드 스쿼트/트위스트'
 '바이시클 크런치' '점핑 런지' '다리벌려 숙이기' '다리벌려 한쪽 발목 잡기']

===== ftns_lvl_nm =====
[API 1]
['중급' '3' '초급' '4~5' '1~5' '3~5' '2~5' '5' '1~2' '1' '공통' '3~5, 1~5']

[API 3]
해당 컬럼 없음

===== rptt_tcnt_nm =====
[API 1]
['10~15' '3~5' '2~3' '2~4' '3~3' '10~20' '20~30' '6~8' '8~10' '2~2'
 '15~15' '2~10' '3~6' '8~12' '3~9' '6~10']

[API 3]
['10~15' '20~30' '10~20' '2~3' '3~5' '10~30' '2~4' '2~2' '2~6' '2~5'
 '5~20' '5~15' '5~10' '10~10']

===== set_cnt_nm =====
[API 1]
['1~3' '1~1' '3~3' '3~5' '2~3' '1~2' '1~5' '2~2']


In [397]:
# 실내 운동 중 분류가 필요한 도구가 어떤 운동에 사용되는지 확인

check_tools = [
    "라바콘", "콘", "하프콘",
    "테니스공",
    "바", "봉", "막대", "막대기", "플렉스 바",
    "풍선", "스카프", "줄", "지팡이",
    "박스",
    "색테이프", "발판", "고무줄",
    "허들", "색깔판"
]

def check_tool_exercises(df, api_name):
    result = (
        df[
            (df["trng_plc_nm"] == "실내") &
            (df["tool_nm"].isin(check_tools))
        ]
        [["tool_nm", "trng_nm", "vdo_ttl_nm"]]
        .drop_duplicates()
        .sort_values(["tool_nm", "trng_nm"])
    )

    print(f"[{api_name}]")
    display(result)


check_tool_exercises(api1, "API 1")
check_tool_exercises(api3, "API 3")

[API 1]

     tool_nm              trng_nm           vdo_ttl_nm
19       라바콘      앉아서 엉덩이 들고 이동하기      앉아서 엉덩이 들고 이동하기
2129      막대    누워서 막대 잡고 팔 들어올리기    누워서 막대 잡고 팔 들어올리기
2153      막대     누워서 막대 잡고 팔 회전하기     누워서 막대 잡고 팔 회전하기
2159      막대  막대 잡고 대각선으로 팔 들어올리기  막대 잡고 대각선으로 팔 들어올리기
2122      막대     막대 잡고 팔 안쪽/바깥 돌림     막대 잡고 팔 안쪽/바깥 돌림
2297      막대            옆구리 늘리기-1              아쿠아로빅-2
724        바            연속 무릎 올리기            연속 무릎 올리기
5965      박스            다리 뻗어 올리기            다리 뻗어 올리기
5884      박스           뒤로 팔 굽혀 펴기           뒤로 팔굽혀펴기-1
5409      박스      사이드 스텝 점프하기(박스)          사이드 스텝 점프하기
5386      박스       양발 점프 착지하기(박스)           양발 점프 착지하기
5396      박스         점프 후 버티기(박스)             점프 후 버티기
2579       봉        봉 잡고 앉았다 일어서기        봉 잡고 앉았다 일어서기
4481       봉      봉 잡고 앉았다 일어서기-1     관절염 예방을 위한 근력운동1
4236       줄              줄 따라 걷기              줄 따라 걷기
4279     지팡이              의자 이용하기              의자 이용하기
765        콘              반복 옆 뛰기              반복 옆 뛰기
813     테니스공                 벽 패스                 벽 패스
4206      풍선                 성화봉송                 성화봉송
2668   플렉스 바            플렉스 바 비틀기            플렉스 바 비틀기
751      하프콘         점프하며 앞으로 나가기         점프하며 앞으로 나가기

[API 3]

     tool_nm              trng_nm            vdo_ttl_nm
1490     고무줄               고무줄 놀이            고무줄 놀이를 해요
1486     고무줄             딩링링을 끼워요              딩딩링을 끼워요
1444     라바콘               사이드 스텝              (기본편)민첩성
1439     라바콘             엉긍엉금 기어요              엉금엉금 기어요
1438     라바콘         엉긍엉금 기어요(준비)              엉금엉금 기어요
1366      막대    누워서 막대 잡고 팔 들어올리기     누워서 막대 잡고 팔 들어올리기
1373      막대     누워서 막대 잡고 팔 회전하기      누워서 막대 잡고 팔 회전하기
1378      막대  막대 잡고 대각선으로 팔 들어올리기   막대 잡고 대각선으로 팔 들어올리기
1363      막대     막대 잡고 팔 안쪽 바깥 돌림      막대 잡고 팔 안쪽?바깥 돌림
1482      발판        뽁뽁이를 밟아요(발가락)         뽁뽁이를 밟아요(발가락)
1525      발판               장애물 걷기           알록달록 공을 옮겨요
1058       봉     누워서 봉 뒤로 내리고 당기기      누워서 공 뒤로 내리고 당기기
753        봉         봉잡고 앉았다 일어나기          봉잡고 앉았다 일어나기
792     색테이프                균형 걷기                 균형 걷기
795     색테이프               발교차 걷기                 균형 걷기
1517     지팡이                   걷기               지게발 걸어요
118     테니스공                   가슴  테니스공을 활용한 뭉친근육 완화 운동
150     테니스공                 목 상부  테니스공을 활용한 뭉친근육 완화 운동
482     테니스공                 목 외측  테니스공을 활용한 뭉친근육 완화 운동
129     테니스공               전완(내측)  테니스공을 활용한 뭉친근육 완화 운동
882     테니스공               전완(외측)  테니스공을 활용한 뭉친근육 완화 운동
180     테니스공                  정강이  테니스공을 활용한 뭉친근육 완화 운동
170     테니스공              종아리(기본)  테니스공을 활용한 뭉친근육 완화 운동
246     테니스공                   허리  테니스공을 활용한 뭉친근육 완화 운동
160     테니스공            허벅지(햄스트링)  테니스공을 활용한 뭉친근육 완화 운동
1495      풍선              공 치기(손)           (기본편)조작성 운동
1555      풍선             풍선치기(라켓)             풍선 테니스 해요
1553      풍선          풍선치기(라켓-언더)             풍선 테니스 해요
1554      풍선          풍선치기(라켓-오버)             풍선 테니스 해요

In [398]:
# 운동 도구를 기본 생활도구, 선택 보유도구, 추천 제외도구로 분류

basic_tools = [
    "매트",
    "물병",
    "물통",
    "의자",
    "테이블",
    "소파",
    "수건",
    "베개",
    "벽",
    "막대",
    "봉",
    "줄"
]

optional_tools = [
    "아령",
    "덤벨",
    "밴드",
    "써클링",
    "써클휠",
    "짐볼",
    "큰공",
    "공",
    "줄넘기",
    "스텝박스",
    "스텝퍼",
    "스탭퍼",
    "보슈",
    "사다리",
    "줄사다리",
    "폼롤러",
    "바벨",
    "원판",
    "메디신볼",
    "훌라후프",
    "테니스공",
    "박스"
]

excluded_tools = [
    "헬스기구",
    "실내자전거",
    "트레드밀",
    "자전거",
    "벤치",
    "아쿠아봉",
    "킥판",
    "농구공",
    "배드민턴 라켓",
    "계이름 판",
    "라바콘",
    "콘",
    "하프콘",
    "색테이프",
    "발판",
    "지팡이",
    "풍선",
    "고무줄",
    "플렉스 바",
    "막대기",
    "바",
    "색깔판",
    "스카프",
    "허들",
    "헬멧",
    "작은공",
    "계단"
]

alternative_tools = [
    "물병(밴드)",
    "수건(낮은 쿠션)",
    "봉(의자)"
]

In [399]:
# 모든 운동 도구가 기본·선택·제외·대체 도구 중 하나로 분류되었는지 최종 확인

classified_tools = set(
    basic_tools
    + optional_tools
    + excluded_tools
    + alternative_tools
)

api1_tools = set(api1["tool_nm"].dropna().unique())
api3_tools = set(api3["tool_nm"].dropna().unique())

unclassified_tools = sorted(
    (api1_tools | api3_tools) - classified_tools
)

print("미분류 도구 수:", len(unclassified_tools))
print(unclassified_tools)

미분류 도구 수: 0
[]

In [400]:
# API 1·3의 연령대 종류와 콘텐츠 유형 종류만 간단히 확인

print("API 1 연령대:", api1["aggrp_nm"].dropna().unique().tolist())
print("API 3 연령대:", api3["aggrp_nm"].dropna().unique().tolist())

print("API 1 콘텐츠 유형:", api1["data_type"].dropna().unique().tolist())
print("API 3 콘텐츠 유형:", api3["data_type"].dropna().unique().tolist())

API 1 연령대: ['유소년', '청소년', '공통', '어르신']
API 3 연령대: ['공통', '유아기']
API 1 콘텐츠 유형: ['동영상']
API 3 콘텐츠 유형: ['동영상']

In [401]:
# 1차 필터링된 API 1과 API 3 사이에 동일한 영상(file_nm)이 존재하는지 확인

api1_files = set(api1_filtered["file_nm"].unique())
api3_files = set(api3_filtered["file_nm"].unique())

common_files = sorted(api1_files & api3_files)

print("API 1 영상 수:", len(api1_files))
print("API 3 영상 수:", len(api3_files))
print("API 1·3 중복 영상 수:", len(common_files))
print("통합 후 예상 영상 수:", len(api1_files | api3_files))

print("\n중복 file_nm:")
print(common_files)

API 1 영상 수: 283
API 3 영상 수: 115
API 1·3 중복 영상 수: 0
통합 후 예상 영상 수: 398

중복 file_nm:
[]

In [402]:
# 필터 통과 영상 중 원본 데이터에 제외 도구가 함께 포함되어 있던 영상이 있는지 확인

filtered_files = set(api1_filtered["file_nm"]) | set(api3_filtered["file_nm"])

excluded_tool_videos_api1 = api1[
    (api1["file_nm"].isin(filtered_files))
    & (api1["tool_nm"].isin(excluded_tools))
][["file_nm", "vdo_ttl_nm", "tool_nm"]].drop_duplicates()

excluded_tool_videos_api3 = api3[
    (api3["file_nm"].isin(filtered_files))
    & (api3["tool_nm"].isin(excluded_tools))
][["file_nm", "vdo_ttl_nm", "tool_nm"]].drop_duplicates()

print("[API 1]")
display(excluded_tool_videos_api1)

print("\n[API 3]")
display(excluded_tool_videos_api3)

print("\n제외 도구가 함께 존재하는 영상 수")
print(
    len(
        set(excluded_tool_videos_api1["file_nm"])
        | set(excluded_tool_videos_api3["file_nm"])
    )
)

[API 1]

Empty DataFrame
Columns: [file_nm, vdo_ttl_nm, tool_nm]
Index: []

[API 3]

Empty DataFrame
Columns: [file_nm, vdo_ttl_nm, tool_nm]
Index: []

제외 도구가 함께 존재하는 영상 수
0

In [403]:
# 필터 통과 영상에 인원·장소·연령대 조건을 만족하지 않는 행이 함께 존재하는지 확인

api1_filtered_files = set(api1_filtered["file_nm"])
api3_filtered_files = set(api3_filtered["file_nm"])

# API 1: 같은 영상에 2인 이상 또는 3인 이상 조건이 함께 있는지 확인
api1_invalid_nope = api1[
    (api1["file_nm"].isin(api1_filtered_files))
    & (~api1["nope_nm"].isin(["1인 이상"]))
    & (api1["nope_nm"].notna())
][["file_nm", "vdo_ttl_nm", "nope_nm"]].drop_duplicates()

# API 1: 같은 영상에 실내가 아닌 장소가 함께 있는지 확인
api1_invalid_place = api1[
    (api1["file_nm"].isin(api1_filtered_files))
    & (api1["trng_plc_nm"] != "실내")
][["file_nm", "vdo_ttl_nm", "trng_plc_nm"]].drop_duplicates()

# API 3: 같은 영상에 실내가 아닌 장소가 함께 있는지 확인
api3_invalid_place = api3[
    (api3["file_nm"].isin(api3_filtered_files))
    & (api3["trng_plc_nm"] != "실내")
][["file_nm", "vdo_ttl_nm", "trng_plc_nm"]].drop_duplicates()

# API 1: 같은 영상에 MVP 대상이 아닌 연령대가 함께 있는지 확인
api1_invalid_age = api1[
    (api1["file_nm"].isin(api1_filtered_files))
    & (~api1["aggrp_nm"].isin(["청소년", "공통"]))
][["file_nm", "vdo_ttl_nm", "aggrp_nm"]].drop_duplicates()

# API 3: 같은 영상에 공통이 아닌 연령대가 함께 있는지 확인
api3_invalid_age = api3[
    (api3["file_nm"].isin(api3_filtered_files))
    & (api3["aggrp_nm"] != "공통")
][["file_nm", "vdo_ttl_nm", "aggrp_nm"]].drop_duplicates()

print("API 1 인원 충돌 영상:", api1_invalid_nope["file_nm"].nunique())
print("API 1 장소 충돌 영상:", api1_invalid_place["file_nm"].nunique())
print("API 3 장소 충돌 영상:", api3_invalid_place["file_nm"].nunique())
print("API 1 연령대 충돌 영상:", api1_invalid_age["file_nm"].nunique())
print("API 3 연령대 충돌 영상:", api3_invalid_age["file_nm"].nunique())

API 1 인원 충돌 영상: 0
API 1 장소 충돌 영상: 117
API 3 장소 충돌 영상: 8
API 1 연령대 충돌 영상: 0
API 3 연령대 충돌 영상: 0

In [404]:
# API 1에서 실내와 다른 장소 정보가 함께 등록된 7개 영상의 장소값과 운동명 확인

api1_place_conflict_files = api1_invalid_place["file_nm"].unique()

api1_place_conflicts = (
    api1[
        api1["file_nm"].isin(api1_place_conflict_files)
    ]
    [["file_nm", "vdo_ttl_nm", "trng_nm", "trng_plc_nm"]]
    .drop_duplicates()
    .sort_values(["file_nm", "trng_plc_nm", "trng_nm"])
)

display(api1_place_conflicts)

,file_nm,vdo_ttl_nm,trng_nm,trng_plc_nm
831,0AUDLJ08S_00459.mp4,걷기,걷기,실내/실외
836,0AUDLJ08S_00460.mp4,달리기,달리기,실내/실외
1230,0AUDLJ08S_00509.mp4,덤벨 옆으로 들어올리기,덤벨 옆으로 들어올리기,실내/실외
1320,0AUDLJ08S_00519.mp4,앉았다 일어서기-1,앉았다 일어서기,실내/실외
1336,0AUDLJ08S_00521.mp4,한발 앞으로 내밀고 앉았다 일어서기,한발 앞으로 내밀고 앉았다 일어서기,실내/실외
...,...,...,...,...
8095,0AUDLJ08S_01007.mp4,유연성운동 루틴프로그램-2,엎드려 상체 들어올리기-2,실내/실외
8103,0AUDLJ08S_01007.mp4,유연성운동 루틴프로그램-2,의자에 앉아 가슴 뒤로 젖히기-1,실내/실외
8032,0AUDLJ08S_01007.mp4,유연성운동 루틴프로그램-2,척추 들어올리기-1,실내/실외
7147,0AUDLJ08S_01007.mp4,유연성운동 루틴프로그램-2,팔꿈치 머리 뒤로 젖히기-1,실내/실외
8086,0AUDLJ08S_01007.mp4,유연성운동 루틴프로그램-2,NaN,실내/실외

In [405]:
# 실내에서 수행 가능한 장소(실내·실내/실외 계열)를 포함하도록 API 1·3의 1차 추천 후보를 다시 생성

indoor_places = [
    "실내",
    "실내/실외",
    "실내, 실외"
]

api1_filtered = api1[
    (api1["trng_plc_nm"].isin(indoor_places))
    & (~api1["tool_nm"].isin(excluded_tools))
    & (api1["nope_nm"] == "1인 이상")
    & (api1["vdo_len"] < 600)
    & (api1["aggrp_nm"].isin(["청소년", "공통"]))
].copy()

api3_filtered = api3[
    (api3["trng_plc_nm"].isin(indoor_places))
    & (~api3["tool_nm"].isin(excluded_tools))
    & (api3["vdo_len"] < 600)
    & (api3["aggrp_nm"] == "공통")
].copy()

print("[API 1]")
print("필터링 후 행:", len(api1_filtered))
print("필터링 후 영상:", api1_filtered["file_nm"].nunique())

print("\n[API 3]")
print("필터링 후 행:", len(api3_filtered))
print("필터링 후 영상:", api3_filtered["file_nm"].nunique())

[API 1]
필터링 후 행: 3659
필터링 후 영상: 287

[API 3]
필터링 후 행: 851
필터링 후 영상: 116

In [406]:
# 제외 도구가 하나라도 포함된 영상은 해당 file_nm의 모든 행을 추천 후보에서 제외

excluded_file_nm_api1 = set(
    api1[
        api1["tool_nm"].isin(excluded_tools)
    ]["file_nm"]
)

excluded_file_nm_api3 = set(
    api3[
        api3["tool_nm"].isin(excluded_tools)
    ]["file_nm"]
)

api1_filtered = api1_filtered[
    ~api1_filtered["file_nm"].isin(excluded_file_nm_api1)
].copy()

api3_filtered = api3_filtered[
    ~api3_filtered["file_nm"].isin(excluded_file_nm_api3)
].copy()

print("[API 1]")
print("남은 행:", len(api1_filtered))
print("남은 영상:", api1_filtered["file_nm"].nunique())

print("\n[API 3]")
print("남은 행:", len(api3_filtered))
print("남은 영상:", api3_filtered["file_nm"].nunique())

print(
    "\n총 영상:",
    api1_filtered["file_nm"].nunique()
    + api3_filtered["file_nm"].nunique()
)

[API 1]
남은 행: 3639
남은 영상: 283

[API 3]
남은 행: 850
남은 영상: 115

총 영상: 398

In [407]:
# 최종 필터링된 데이터에서 같은 영상(file_nm) 내 여러 값을 가지는 컬럼 확인

def check_multi_values(df, video_col="file_nm"):
    result = []

    for col in df.columns:
        if col == video_col:
            continue

        max_unique = df.groupby(video_col)[col].nunique().max()

        if max_unique > 1:
            result.append({
                "column": col,
                "max_values_per_video": max_unique
            })

    return pd.DataFrame(result).sort_values(
        "max_values_per_video",
        ascending=False
    )

print("[API 1]")
display(check_multi_values(api1_filtered))

print("[API 3]")
display(check_multi_values(api3_filtered))

[API 1]

              column  max_values_per_video
3            row_num                    71
5            frme_no                    71
17       img_file_sn                    71
7        img_file_nm                    71
14           snap_tm                    71
0       trng_mscl_nm                    10
8    trng_mscl_zn_nm                    10
16  trng_mscl_eng_nm                    10
10    trng_mscl_part                    10
11           trng_nm                     9
13   trng_mscl_class                     9
2        ftns_lvl_nm                     3
4            tool_nm                     3
12           job_ymd                     3
15        trng_hr_nm                     2
9        trng_plc_nm                     2
1       rptt_tcnt_nm                     2
6       ecrg_cycl_nm                     2
18        set_cnt_nm                     2

[API 3]

              column  max_values_per_video
1            row_num                    29
3            frme_no                    29
4        img_file_nm                    29
10           snap_tm                    29
13       img_file_sn                    29
0       trng_mscl_nm                    15
5    trng_mscl_zn_nm                    15
12  trng_mscl_eng_nm                    15
6     trng_mscl_part                    14
7            trng_nm                    14
9    trng_mscl_class                    14
2            tool_nm                     4
8            job_ymd                     2
11        trng_hr_nm                     2

In [408]:
# 프레임·이미지·관리용 컬럼을 제거하여 영상 단위 집계를 위한 데이터 준비

drop_cols = [
    "row_num",
    "frme_no",
    "snap_tm",
    "img_file_sn",
    "img_file_nm",
    "job_ymd"
]

api1_filtered = api1_filtered.drop(
    columns=[col for col in drop_cols if col in api1_filtered.columns]
).copy()

api3_filtered = api3_filtered.drop(
    columns=[col for col in drop_cols if col in api3_filtered.columns]
).copy()

print("API 1 컬럼 수:", len(api1_filtered.columns))
print(api1_filtered.columns.tolist())

print("\nAPI 3 컬럼 수:", len(api3_filtered.columns))
print(api3_filtered.columns.tolist())

API 1 컬럼 수: 29
['trng_mscl_nm', 'rptt_tcnt_nm', 'file_url', 'vdo_desc', 'file_sz', 'fps_cnt', 'ftns_lvl_nm', 'resolution', 'tool_nm', 'aggrp_nm', 'ecrg_cycl_nm', 'trng_mscl_zn_nm', 'fbctn_yr', 'nope_nm', 'trng_plc_nm', 'vdo_len', 'trng_mscl_part', 'lang', 'trng_nm', 'ftns_fctr_nm', 'trng_mscl_class', 'vdo_ttl_nm', 'trng_hr_nm', 'file_type_nm', 'file_nm', 'trng_mscl_eng_nm', 'img_file_url', 'data_type', 'set_cnt_nm']

API 3 컬럼 수: 26
['trng_mscl_nm', 'rptt_tcnt_nm', 'file_url', 'vdo_desc', 'file_sz', 'fps_cnt', 'resolution', 'tool_nm', 'aggrp_nm', 'ecrg_cycl_nm', 'trng_mscl_zn_nm', 'fbctn_yr', 'trng_plc_nm', 'vdo_len', 'trng_mscl_part', 'lang', 'trng_nm', 'trng_mscl_class', 'vdo_ttl_nm', 'trng_hr_nm', 'file_type_nm', 'file_nm', 'trng_mscl_eng_nm', 'img_file_url', 'data_type', 'set_cnt_nm']

In [409]:
# file_nm 기준으로 여러 행을 영상당 1행으로 집계하고 실제 영상 URL 생성

multi_cols_api1 = [
    "trng_mscl_nm",
    "rptt_tcnt_nm",
    "ftns_lvl_nm",
    "tool_nm",
    "ecrg_cycl_nm",
    "trng_mscl_zn_nm",
    "trng_plc_nm",
    "trng_mscl_part",
    "trng_nm",
    "ftns_fctr_nm",
    "trng_mscl_class",
    "trng_hr_nm",
    "trng_mscl_eng_nm",
    "set_cnt_nm"
]

multi_cols_api3 = [
    "trng_mscl_nm",
    "rptt_tcnt_nm",
    "tool_nm",
    "ecrg_cycl_nm",
    "trng_mscl_zn_nm",
    "trng_plc_nm",
    "trng_mscl_part",
    "trng_nm",
    "trng_mscl_class",
    "trng_hr_nm",
    "trng_mscl_eng_nm",
    "set_cnt_nm"
]

def join_unique(series):
    values = series.dropna().astype(str).unique()
    return "|".join(values)

def aggregate_videos(df, multi_cols):
    agg_dict = {}

    for col in df.columns:
        if col == "file_nm":
            continue

        if col in multi_cols:
            agg_dict[col] = join_unique
        else:
            agg_dict[col] = "first"

    result = (
        df.groupby("file_nm", as_index=False)
        .agg(agg_dict)
    )

    result["video_url"] = (
        result["file_url"].fillna("")
        + result["file_nm"].fillna("")
    )

    return result


api1_video = aggregate_videos(api1_filtered, multi_cols_api1)
api3_video = aggregate_videos(api3_filtered, multi_cols_api3)

print("API 1 영상:", len(api1_video))
print("API 3 영상:", len(api3_video))
print("총 영상:", len(api1_video) + len(api3_video))

API 1 영상: 283
API 3 영상: 115
총 영상: 398

In [410]:
# 영상 URL 생성 및 다중값 집계 결과가 정상인지 API별 샘플을 확인

check_cols_api1 = [
    "file_nm",
    "video_url",
    "vdo_ttl_nm",
    "trng_nm",
    "tool_nm",
    "ftns_fctr_nm",
    "rptt_tcnt_nm",
    "set_cnt_nm"
]

check_cols_api3 = [
    "file_nm",
    "video_url",
    "vdo_ttl_nm",
    "trng_nm",
    "tool_nm",
    "rptt_tcnt_nm",
    "set_cnt_nm"
]

print("[API 1]")
display(api1_video[check_cols_api1].head(5))

print("[API 3]")
display(api3_video[check_cols_api3].head(5))

[API 1]

,file_nm,video_url,vdo_ttl_nm,trng_nm,tool_nm,ftns_fctr_nm,rptt_tcnt_nm,set_cnt_nm
0,0AUDLJ08S_00459.mp4,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,걷기,걷기,,전신지구력,,
1,0AUDLJ08S_00460.mp4,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,달리기,달리기,,전신지구력,,
2,0AUDLJ08S_00464.mp4,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,줄넘기,줄넘기,줄넘기,심폐지구력,,
3,0AUDLJ08S_00491.mp4,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,원판 던지기,원판 던지기,원판,근력,,
4,0AUDLJ08S_00500.mp4,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,몸통 옆으로 굽히기,몸통 옆으로 굽히기,덤벨,근력,,

[API 3]

,file_nm,video_url,vdo_ttl_nm,trng_nm,tool_nm,rptt_tcnt_nm,set_cnt_nm
0,0AUDLJ08S_00185.mp4,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,줄넘기,양발 넘기기|한발 넘기기,줄넘기,,
1,0AUDLJ08S_00186.mp4,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,계단 올라갔다 내려오기,계단 올라갔다 내려오기,,,
2,0AUDLJ08S_00187.mp4,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,계단 뛰어 오르기,계단 뛰어 오르기,,,
3,0AUDLJ08S_00188.mp4,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,스텝박스 오르내리기,스텝박스 오르내리기,,,
4,0AUDLJ08S_00189.mp4,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,엎드려 양발 교차로 당기기,엎드려 양발 교차로 당기기,,,

In [411]:
# 제외 도구명이 운동명 또는 영상 제목에 포함됐지만 tool_nm에는 제대로 기록되지 않은 후보 영상을 확인

def find_excluded_tool_in_text(df):
    results = []

    for _, row in df.iterrows():
        text = " ".join([
            str(row.get("vdo_ttl_nm", "")),
            str(row.get("trng_nm", ""))
        ])

        matched_tools = [
            tool for tool in excluded_tools
            if tool in text
        ]

        if matched_tools:
            results.append({
                "file_nm": row["file_nm"],
                "vdo_ttl_nm": row["vdo_ttl_nm"],
                "trng_nm": row["trng_nm"],
                "tool_nm": row["tool_nm"],
                "matched_excluded_tools": "|".join(matched_tools)
            })

    return pd.DataFrame(results)


api1_text_check = find_excluded_tool_in_text(api1_video)
api3_text_check = find_excluded_tool_in_text(api3_video)

print("[API 1]")
display(api1_text_check)

print("\n[API 3]")
display(api3_text_check)

[API 1]

,file_nm,vdo_ttl_nm,trng_nm,tool_nm,matched_excluded_tools
0,0AUDLJ08S_00504.mp4,서서 바벨 위로 밀기,서서 바벨 위로 밀기,바벨|덤벨,바
1,0AUDLJ08S_00527.mp4,서서 다리로 턴력밴드 당기기Ⅱ,안으로 당기기|바깥으로 당기기,밴드,바
2,0AUDLJ08S_00530.mp4,방등 굽힘/발바닥 굽힘,방등 굽힘/발바닥 굽힘,수건,바
3,0AUDLJ08S_00543.mp4,누워서 하늘 자전거,누워서 하늘 자전거,소파,자전거
4,0AUDLJ08S_00548.mp4,네발기기 자세에서 손바닥으로 바닥밀기,네발기기 자세에서 손바닥으로 바닥밀기,매트,바
5,0AUDLJ08S_00612.mp4,막대 잡고 팔 안쪽/바깥 돌림,막대 잡고 팔 안쪽/바깥 돌림,막대,바
6,0AUDLJ08S_00620.mp4,등척성 운동(바깥돌림),등척성 운동(바깥돌림),수건,바
7,0AUDLJ08S_00875.mp4,바로서서 상체 숙이기,바로서서 상체 숙이기,,바
8,0AUDLJ08S_00890.mp4,발 바꿔 뛰기,발 바꿔 뛰기,,바
9,0AUDLJ08S_00965.mp4,전진 점프하며 발바닥 찍기,전진 점프하며 발바닥 찍기,,바
10,0AUDLJ08S_01000.mp4,근력·근지구력운동 루틴프로그램,팔 굽혀 펴기-1|몸통 들어올리기-1|바로서서 상체 숙이기-1|손 뻗어 윗몸 일으키...,매트,바

[API 3]

,file_nm,vdo_ttl_nm,trng_nm,tool_nm,matched_excluded_tools
0,0AUDLJ08S_00186.mp4,계단 올라갔다 내려오기,계단 올라갔다 내려오기,,계단
1,0AUDLJ08S_00187.mp4,계단 뛰어 오르기,계단 뛰어 오르기,,계단
2,0AUDLJ08S_00242.mp4,누워서 하늘 자전거,누워서 하늘 자전거,소파,자전거
3,0AUDLJ08S_00246.mp4,네발기기 자세에서 손바닥으로 바닥밀기,네발기기 자세에서 손바닥으로 바닥밀기,매트,바
4,0AUDLJ08S_00276.mp4,서서 다리로 탄력밴드 당기기 II,안으로 당기기|바깥으로 당기기,밴드,바
5,0AUDLJ08S_00277.mp4,발등굽힘/발바닥굽힘,발바닥 굽힘|발등 굽힘|가쪽번짐,밴드|수건,바
6,0AUDLJ08S_00338.mp4,막대 잡고 팔 안쪽?바깥 돌림,막대 잡고 팔 안쪽 바깥 돌림,막대,바
7,0AUDLJ08S_00344.mp4,등척성운동-바깥돌림,바깥돌림,수건,바
8,0AUDLJ08S_01020.mp4,5분 타바타 운동(상체),파이크 푸시업|점핑 잭|제자리 걸으면서 손목 돌리기|다리 어깨너비로 벌려 팔꿈치 돌...,매트,바

In [412]:
# tool_nm 누락 계단 운동 2개와 9분(540초) 이상 영상을 추천 후보에서 제외

excluded_file_nm_manual = [
    "0AUDLJ08S_00186.mp4",
    "0AUDLJ08S_00187.mp4"
]

api1_video = api1_video[
    api1_video["vdo_len"] < 540
].copy()

api3_video = api3_video[
    (~api3_video["file_nm"].isin(excluded_file_nm_manual))
    & (api3_video["vdo_len"] < 540)
].copy()

print("API 1 영상:", len(api1_video))
print("API 3 영상:", len(api3_video))
print("총 영상:", len(api1_video) + len(api3_video))

API 1 영상: 283
API 3 영상: 112
총 영상: 395

In [413]:
# 최종 추천 후보 영상의 길이를 1분 단위 구간으로 나누어 API별 영상 수와 비율을 표로 확인

def video_length_table(df):
    bins = [0, 60, 120, 180, 240, 300, 360, 420, 480, 540, 600]
    labels = [
        "1분 미만",
        "1~2분",
        "2~3분",
        "3~4분",
        "4~5분",
        "5~6분",
        "6~7분",
        "7~8분",
        "8~9분",
        "9~10분"
    ]

    length_group = pd.cut(
        df["vdo_len"],
        bins=bins,
        labels=labels,
        right=False
    )

    result = (
        length_group
        .value_counts(sort=False)
        .rename("영상 수")
        .to_frame()
    )

    result["비율(%)"] = (
        result["영상 수"] / len(df) * 100
    ).round(1)

    return result


print("[API 1]")
display(video_length_table(api1_video))

print("[API 3]")
display(video_length_table(api3_video))

[API 1]

         영상 수  비율(%)
vdo_len
1분 미만      46   16.3
1~2분      212   74.9
2~3분       15    5.3
3~4분        7    2.5
4~5분        3    1.1
5~6분        0    0.0
6~7분        0    0.0
7~8분        0    0.0
8~9분        0    0.0
9~10분       0    0.0

[API 3]

         영상 수  비율(%)
vdo_len
1분 미만      45   40.2
1~2분       62   55.4
2~3분        2    1.8
3~4분        1    0.9
4~5분        1    0.9
5~6분        1    0.9
6~7분        0    0.0
7~8분        0    0.0
8~9분        0    0.0
9~10분       0    0.0

In [414]:
# API별 최종 추천 후보 영상의 최소·평균·중앙값·최대 영상 길이를 초와 분 단위로 요약

length_summary = pd.DataFrame({
    "API": ["API 1", "API 3"],
    "영상 수": [len(api1_video), len(api3_video)],
    "최소(초)": [api1_video["vdo_len"].min(), api3_video["vdo_len"].min()],
    "평균(초)": [api1_video["vdo_len"].mean(), api3_video["vdo_len"].mean()],
    "중앙값(초)": [api1_video["vdo_len"].median(), api3_video["vdo_len"].median()],
    "최대(초)": [api1_video["vdo_len"].max(), api3_video["vdo_len"].max()]
})

length_summary["평균(분)"] = (length_summary["평균(초)"] / 60).round(2)
length_summary["중앙값(분)"] = (length_summary["중앙값(초)"] / 60).round(2)

display(length_summary)

     API  영상 수  최소(초)      평균(초)  중앙값(초)  최대(초)  평균(분)  중앙값(분)
0  API 1   283     44  87.325088    80.0    275   1.46    1.33
1  API 3   112     34  71.312500    63.5    331   1.19    1.06

In [415]:
# 최종 추천 후보 영상이 API별로 어떤 연령대로 구성되어 있는지 확인

print("[API 1]")
display(
    api1_video["aggrp_nm"]
    .value_counts(dropna=False)
    .rename_axis("연령대")
    .reset_index(name="영상 수")
)

print("\n[API 3]")
display(
    api3_video["aggrp_nm"]
    .value_counts(dropna=False)
    .rename_axis("연령대")
    .reset_index(name="영상 수")
)

[API 1]

   연령대  영상 수
0  청소년   157
1   공통   126

[API 3]

  연령대  영상 수
0  공통   112

In [416]:
# 최종 필터링된 API 1·3 영상 데이터를 하나의 데이터셋으로 통합하고 출처 API를 기록

api1_video["source_api"] = "API 1"
api3_video["source_api"] = "API 3"

workout_videos = pd.concat(
    [api1_video, api3_video],
    ignore_index=True,
    sort=False
)

print("통합 영상 수:", len(workout_videos))
print("고유 file_nm 수:", workout_videos["file_nm"].nunique())
print("컬럼 수:", len(workout_videos.columns))

print("\nAPI별 영상 수")
display(
    workout_videos["source_api"]
    .value_counts()
    .rename_axis("API")
    .reset_index(name="영상 수")
)

통합 영상 수: 395
고유 file_nm 수: 395
컬럼 수: 31

API별 영상 수

     API  영상 수
0  API 1   283
1  API 3   112

In [417]:
# 통합 데이터의 31개 컬럼별 자료형·결측치·고유값 수·샘플값을 확인해 최종 사용 컬럼을 선정

column_check = pd.DataFrame({
    "column": workout_videos.columns,
    "dtype": workout_videos.dtypes.astype(str).values,
    "missing": workout_videos.isna().sum().values,
    "missing_ratio(%)": (
        workout_videos.isna().mean().values * 100
    ).round(1),
    "unique_count": [
        workout_videos[col].nunique(dropna=True)
        for col in workout_videos.columns
    ],
    "sample": [
        " | ".join(
            workout_videos[col]
            .dropna()
            .astype(str)
            .unique()[:3]
        )
        for col in workout_videos.columns
    ]
})

display(column_check)

,column,dtype,missing,missing_ratio(%),unique_count,sample
0,file_nm,object,0,0.0,395,0AUDLJ08S_00459.mp4 | 0AUDLJ08S_00460.mp4 | 0A...
1,trng_mscl_nm,object,0,0.0,266,"볼기근,가자미근,넙다리네갈래근,장딴지근 | 위팔두갈래근,넙다리두갈래근,장딴지근 | ..."
2,rptt_tcnt_nm,object,0,0.0,11,| 10~20 | 10~15
3,file_url,object,0,0.0,1,http://openapi.kspo.or.kr/web/video/
4,vdo_desc,object,0,0.0,383,"유산소 운동 중, 걷기운동을 설명한 운동처방 가이드 동영상 | 전신지구력 운동 중,..."
5,file_sz,int64,0,0.0,395,10516825 | 9770930 | 10972445
6,fps_cnt,float64,0,0.0,2,29.96 | 29.97
7,ftns_lvl_nm,object,112,28.4,15,1~5 | 3~5 | 5
8,resolution,object,0,0.0,2,1280*720 | 960*540
9,tool_nm,object,0,0.0,50,| 줄넘기 | 원판
10,aggrp_nm,object,0,0.0,2,공통 | 청소년
11,ecrg_cycl_nm,object,0,0.0,7,| 2~2|2~3 | 3~5
12,trng_mscl_zn_nm,object,0,0.0,266,"둔근,넙치근,대퇴사두근,비복근 | 상완이두근,대퇴이두근,비복근 | 둔근,요근,척추기..."
13,fbctn_yr,int64,0,0.0,4,2011 | 2012 | 2013
14,nope_nm,object,112,28.4,1,1인 이상
15,trng_plc_nm,object,0,0.0,4,실내/실외 | 실내 | 실내|실내/실외
16,vdo_len,int64,0,0.0,108,62 | 58 | 67
17,trng_mscl_part,object,0,0.0,231,"엉덩이,종아리,앞쪽 넓적다리,종아리 | 앞쪽 위팔,뒤쪽 넓적다리,종아리 | 엉덩이,..."
18,lang,object,0,0.0,1,한국어
19,trng_nm,object,0,0.0,341,걷기 | 달리기 | 줄넘기
20,ftns_fctr_nm,object,112,28.4,11,전신지구력 | 심폐지구력 | 근력
21,trng_mscl_class,object,0,0.0,168,"골반의 근,하지의 근,하지의 근,하지의 근 | 상지의 근,하지의 근,하지의 근 | ..."
22,vdo_ttl_nm,object,0,0.0,347,걷기 | 달리기 | 줄넘기
23,trng_hr_nm,object,0,0.0,6,| 10~15 초 | 10~20 초
24,file_type_nm,object,0,0.0,1,mp4
25,trng_mscl_eng_nm,object,0,0.0,266,"Gluteal,Soleus,Quadriceps Femoris,Gastrocnemiu..."
26,img_file_url,object,0,0.0,395,http://openapi.kspo.or.kr/web/image/0AUDLJ08S_...
27,data_type,object,0,0.0,1,동영상
28,set_cnt_nm,object,0,0.0,8,| 1~3 | 3~5
29,video_url,object,0,0.0,395,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...
30,source_api,object,0,0.0,2,API 1 | API 3

In [418]:
# 반복횟수·운동시간·운동주기·세트수 컬럼의 실제 값과 영상 수를 API별로 확인

volume_cols = [
    "rptt_tcnt_nm",
    "trng_hr_nm",
    "ecrg_cycl_nm",
    "set_cnt_nm"
]

for api_name, df in [
    ("API 1", api1_video),
    ("API 3", api3_video)
]:
    print(f"\n========== {api_name} ==========")

    for col in volume_cols:
        print(f"\n[{col}]")

        display(
            df[col]
            .replace("", pd.NA)
            .value_counts(dropna=False)
            .rename_axis("값")
            .reset_index(name="영상 수")
        )

========== API 1 ==========

[rptt_tcnt_nm]

            값  영상 수
0        <NA>   252
1       10~15    13
2       10~20     6
3         2~4     3
4         2~2     3
5  10~15|8~12     2
6       20~30     1
7        8~12     1
8         3~6     1
9         3~9     1

[trng_hr_nm]

                 값  영상 수
0             <NA>   252
1          10~20 초    19
2          10~15 초     7
3          10~30 초     3
4  20~30 초|20~29 초     1
5  14~20 초|15~20 초     1

[ecrg_cycl_nm]

         값  영상 수
0     <NA>   258
1      3~5    14
2      2~3     7
3  2~2|2~3     1
4  3~5|2~3     1
5      3~3     1
6      2~2     1

[set_cnt_nm]

         값  영상 수
0     <NA>   241
1      1~3    20
2      3~5    13
3      1~1     3
4  1~2|2~3     2
5  2~2|2~3     2
6      2~3     1
7      1~2     1

========== API 3 ==========

[rptt_tcnt_nm]

       값  영상 수
0   <NA>   100
1  10~15     6
2  10~20     4
3  20~30     1
4    2~3     1

[trng_hr_nm]

         값  영상 수
0     <NA>    95
1  10~20 초    17

[ecrg_cycl_nm]

      값  영상 수
0  <NA>    97
1   3~5     7
2   3~3     4
3   2~3     4

[set_cnt_nm]

      값  영상 수
0  <NA>    90
1   1~3    16
2   3~5     6

In [419]:
# 반복횟수와 운동시간 정보의 존재 여부 조합을 확인해 exercise_type 자동 분류 가능 범위를 파악

exercise_type_check = workout_videos[
    [
        "source_api",
        "file_nm",
        "vdo_ttl_nm",
        "trng_nm",
        "rptt_tcnt_nm",
        "trng_hr_nm"
    ]
].copy()

exercise_type_check["has_reps"] = (
    exercise_type_check["rptt_tcnt_nm"]
    .fillna("")
    .str.strip()
    .ne("")
)

exercise_type_check["has_time"] = (
    exercise_type_check["trng_hr_nm"]
    .fillna("")
    .str.strip()
    .ne("")
)

exercise_type_check["정보 조합"] = "둘 다 없음"

exercise_type_check.loc[
    exercise_type_check["has_reps"]
    & ~exercise_type_check["has_time"],
    "정보 조합"
] = "횟수만 있음"

exercise_type_check.loc[
    ~exercise_type_check["has_reps"]
    & exercise_type_check["has_time"],
    "정보 조합"
] = "시간만 있음"

exercise_type_check.loc[
    exercise_type_check["has_reps"]
    & exercise_type_check["has_time"],
    "정보 조합"
] = "횟수+시간 모두 있음"

display(
    exercise_type_check
    .groupby(["source_api", "정보 조합"])
    .size()
    .reset_index(name="영상 수")
)

  source_api        정보 조합  영상 수
0      API 1       둘 다 없음   232
1      API 1       시간만 있음    20
2      API 1  횟수+시간 모두 있음    11
3      API 1       횟수만 있음    20
4      API 3       둘 다 없음    88
5      API 3       시간만 있음    12
6      API 3  횟수+시간 모두 있음     5
7      API 3       횟수만 있음     7

In [420]:
# 운동량 정보가 모두 없는 영상들의 운동명 종류와 중복 빈도를 확인

missing_exercise_type = exercise_type_check[
    exercise_type_check["정보 조합"] == "둘 다 없음"
].copy()

missing_trng_count = (
    missing_exercise_type["trng_nm"]
    .value_counts()
    .rename_axis("trng_nm")
    .reset_index(name="영상 수")
)

print("둘 다 없는 영상 수:", len(missing_exercise_type))
print("고유 trng_nm 수:", missing_exercise_type["trng_nm"].nunique())

display(missing_trng_count)

둘 다 없는 영상 수: 320
고유 trng_nm 수: 284

                                               trng_nm  영상 수
0                                             앉았다 일어서기     3
1                                              팔 굽혀 펴기     3
2                                       소파를 이용한 윗몸 올리기     2
3                                              목 굽힘/폄1     2
4                                        허리 굽혀 팔 뒤로 들기     2
..                                                 ...   ...
279                                   메디신 볼 잡고 팔 굽혀 펴기     1
280                                      종아리 사이 감아 돌리기     1
281                                메디신 볼 잡고 런지하며 상체비틀기     1
282                                          볼 잡고 점프하기     1
283  가슴|전완(내측)|목 상부|허벅지(햄스트링)|종아리(기본)|정강이|허리|목 외측|전...     1

[284 rows x 2 columns]

In [421]:
# API 1 최종 후보 영상의 체력요인(ftns_fctr_nm)별 영상 수와 실제 값을 확인

ftns_fctr_count = (
    api1_video["ftns_fctr_nm"]
    .replace("", pd.NA)
    .value_counts(dropna=False)
    .rename_axis("ftns_fctr_nm")
    .reset_index(name="영상 수")
)

display(ftns_fctr_count)

print("고유 체력요인 값 수:", api1_video["ftns_fctr_nm"].nunique())

   ftns_fctr_nm  영상 수
0           유연성   121
1            근력    56
2       근력/근지구력    37
3           순발력    22
4           협응성    17
5       민첩성/순발력    13
6           민첩성    11
7         전신지구력     2
8         심폐지구력     2
9        민첩성/성능     1
10          유산소     1

고유 체력요인 값 수: 11

In [422]:
# API 1과 API 3의 운동명이 정확히 같은 영상을 연결해 API 3에 체력요인을 매핑할 수 있는 범위를 확인

api1_trng_fctr = (
    api1_video[
        ["trng_nm", "vdo_ttl_nm", "ftns_fctr_nm", "file_nm"]
    ]
    .drop_duplicates()
)

api3_trng = (
    api3_video[
        ["trng_nm", "vdo_ttl_nm", "file_nm"]
    ]
    .drop_duplicates()
)

same_trng = api3_trng.merge(
    api1_trng_fctr,
    on="trng_nm",
    how="inner",
    suffixes=("_api3", "_api1")
)

print("API 3 전체 영상:", len(api3_video))
print(
    "정확히 같은 운동명으로 연결된 API 3 영상:",
    same_trng["file_nm_api3"].nunique()
)

print(
    "연결 비율:",
    round(
        same_trng["file_nm_api3"].nunique()
        / len(api3_video) * 100,
        1
    ),
    "%"
)

display(
    same_trng[
        [
            "file_nm_api3",
            "trng_nm",
            "vdo_ttl_nm_api3",
            "ftns_fctr_nm",
            "file_nm_api1"
        ]
    ]
)

API 3 전체 영상: 112
정확히 같은 운동명으로 연결된 API 3 영상: 50
연결 비율: 44.6 %

,file_nm_api3,trng_nm,vdo_ttl_nm_api3,ftns_fctr_nm,file_nm_api1
0,0AUDLJ08S_00231.mp4,서서 상체 일으키기,서서 상체 일으키기,근력,0AUDLJ08S_00518.mp4
1,0AUDLJ08S_00232.mp4,앉았다 일어서기,앉았다 일어서기-1,근력,0AUDLJ08S_00519.mp4
2,0AUDLJ08S_00232.mp4,앉았다 일어서기,앉았다 일어서기-1,근력/근지구력,0AUDLJ08S_00884.mp4
3,0AUDLJ08S_00233.mp4,한발 앞으로 내밀고 앉았다 일어서기,한발 앞으로 내밀고 앉았다 일어서기-1,근력,0AUDLJ08S_00521.mp4
4,0AUDLJ08S_00236.mp4,엎드려 버티기,엎드려 버티기,근력,0AUDLJ08S_00536.mp4
5,0AUDLJ08S_00237.mp4,옆으로 누워 버티기,옆으로 누워 버티기,근력,0AUDLJ08S_00537.mp4
6,0AUDLJ08S_00238.mp4,누워서 다리 들어올리기,누워서 다리 들어올리기,근력,0AUDLJ08S_00538.mp4
7,0AUDLJ08S_00239.mp4,누워서 팔 다리 동시에 들어올리기,누워서 팔 다리 동시에 들어올리기,근력,0AUDLJ08S_00539.mp4
8,0AUDLJ08S_00240.mp4,윗몸 올리기,윗몸올리기,근력,0AUDLJ08S_00533.mp4
9,0AUDLJ08S_00242.mp4,누워서 하늘 자전거,누워서 하늘 자전거,근력,0AUDLJ08S_00543.mp4
10,0AUDLJ08S_00243.mp4,누워서 엉덩이 들어올리기,누워서 엉덩이 들어올리기,근력,0AUDLJ08S_00544.mp4
11,0AUDLJ08S_00245.mp4,엎드려서 팔 다리 들기,엎드려서 팔 다리 들기,근력,0AUDLJ08S_00547.mp4
12,0AUDLJ08S_00246.mp4,네발기기 자세에서 손바닥으로 바닥밀기,네발기기 자세에서 손바닥으로 바닥밀기,근력,0AUDLJ08S_00548.mp4
13,0AUDLJ08S_00247.mp4,네발기기 자세에서 다리 위로 뻗어올리기,네발기기 자세에서 다리 위로 뻗어올리기,근력,0AUDLJ08S_00554.mp4
14,0AUDLJ08S_00248.mp4,팔 굽혀 펴기,팔굽혀펴기,유연성,0AUDLJ08S_00602.mp4
15,0AUDLJ08S_00248.mp4,팔 굽혀 펴기,팔굽혀펴기,근력/근지구력,0AUDLJ08S_00873.mp4
16,0AUDLJ08S_00250.mp4,뒤로 팔 굽혀 펴기,뒤로 팔굽혀펴기,근력/근지구력,0AUDLJ08S_00874.mp4
17,0AUDLJ08S_00251.mp4,허리 굽혀 팔 뒤로 들기,허리 굽혀 팔 뒤로 들기,근력,0AUDLJ08S_00557.mp4
18,0AUDLJ08S_00252.mp4,물병 옆으로 들어올리기,물병 옆으로 들어올리기,근력,0AUDLJ08S_00558.mp4
19,0AUDLJ08S_00253.mp4,팔꿈치 굽히기,팔꿈치 굽히기,근력,0AUDLJ08S_00559.mp4
20,0AUDLJ08S_00254.mp4,목 굽힘/폄1,목 굽힘/폄 I,근력,0AUDLJ08S_00560.mp4
21,0AUDLJ08S_00255.mp4,목 굽힘/폄2,목 굽힘/폄 II,근력,0AUDLJ08S_00561.mp4
22,0AUDLJ08S_00256.mp4,목 굽힘/폄3,목 굽힘/폄 III,근력,0AUDLJ08S_00562.mp4
23,0AUDLJ08S_00264.mp4,의자 앞에서 앉았다 일어서기,의자 앞에서 앉았다 일어서기,근력,0AUDLJ08S_00520.mp4
24,0AUDLJ08S_00265.mp4,의자에 한 다리 올리고 앉았다 일어서기,의자에 한 다리 올리고 앉았다 일어서기,근력,0AUDLJ08S_00522.mp4
25,0AUDLJ08S_00271.mp4,소파를 이용한 윗몸 올리기,소파를 이용한 윗몸올리기,근력,0AUDLJ08S_00535.mp4
26,0AUDLJ08S_00276.mp4,안으로 당기기|바깥으로 당기기,서서 다리로 탄력밴드 당기기 II,근력,0AUDLJ08S_00527.mp4
27,0AUDLJ08S_00278.mp4,탄력밴드 어깨 가쪽 돌림,탄력밴드 어깨 가쪽 돌림,근력,0AUDLJ08S_00551.mp4
28,0AUDLJ08S_00286.mp4,짐볼 윗몸 올리기,짐볼 윗몸올리기,근력,0AUDLJ08S_00534.mp4
29,0AUDLJ08S_00287.mp4,짐볼에 다리 올리고 엉덩이 들어올리기,짐볼에 다리 올리고 엉덩이 들어올리기,근력,0AUDLJ08S_00545.mp4
30,0AUDLJ08S_00288.mp4,짐볼에 엎드려서 팔 다리 들기,짐볼에 엎드려서 팔 다리 들기,근력,0AUDLJ08S_00549.mp4
31,0AUDLJ08S_00298.mp4,누워서 공들고 몸 기울이기,누워서 공들고 몸 기울이기,근력,0AUDLJ08S_00541.mp4
32,0AUDLJ08S_00303.mp4,앉아서 팔꿈치 굽히기/펴기,앉아서팔꿈치굽히기/펴기,근력,0AUDLJ08S_00511.mp4
33,0AUDLJ08S_00305.mp4,엎드려서 균형잡기,엎드려서 균형잡기,근력,0AUDLJ08S_00513.mp4
34,0AUDLJ08S_00306.mp4,윗몸 말아 올리기,윗몸 말아 올리기,근력,0AUDLJ08S_00514.mp4
35,0AUDLJ08S_00307.mp4,엎드려서 다리 차올리기,엎드려서 다리 차올리기,근력,0AUDLJ08S_00515.mp4
36,0AUDLJ08S_00311.mp4,앉았다 일어서면서 점프하기,앉았다 일어서면서 점프하기,민첩성/순발력,0AUDLJ08S_00563.mp4
37,0AUDLJ08S_00312.mp4,무릎 높여 제자리 달리기,무릎 높여 제자리 달리기,민첩성/순발력,0AUDLJ08S_00564.mp4
38,0AUDLJ08S_00313.mp4,옆으로 펀치하기,옆으로 펀치하기,민첩성/순발력,0AUDLJ08S_00565.mp4
39,0AUDLJ08S_00314.mp4,팔 벌려 뛰기,팔벌려뛰기,민첩성/순발력,0AUDLJ08S_00575.mp4
40,0AUDLJ08S_00314.mp4,팔 벌려 뛰기,팔벌려뛰기,순발력,0AUDLJ08S_00832.mp4
41,0AUDLJ08S_00315.mp4,버피 운동,버피운동,민첩성/순발력,0AUDLJ08S_00576.mp4
42,0AUDLJ08S_00316.mp4,점프 팔 굽혀 펴기,점프 팔굽혀펴기,민첩성/순발력,0AUDLJ08S_00577.mp4
43,0AUDLJ08S_00329.mp4,공에 엎드려서 상체 들어올리기,공에 엎드려서 상체 들어올리기,유연성,0AUDLJ08S_00603.mp4
44,0AUDLJ08S_00335.mp4,옆으로 누워서 팔 앞으로 당기기,옆으로 누워서 팔 앞으로 당기기,유연성,0AUDLJ08S_00609.mp4
45,0AUDLJ08S_00337.mp4,테이블 이용하여 팔 옆으로 벌리기,테이블 이용하여 팔 옆으로 벌리기,유연성,0AUDLJ08S_00611.mp4
46,0AUDLJ08S_00339.mp4,누워서 막대 잡고 팔 들어올리기,누워서 막대 잡고 팔 들어올리기,유연성,0AUDLJ08S_00613.mp4
47,0AUDLJ08S_00340.mp4,누워서 막대 잡고 팔 회전하기,누워서 막대 잡고 팔 회전하기,유연성,0AUDLJ08S_00614.mp4
48,0AUDLJ08S_00341.mp4,막대 잡고 대각선으로 팔 들어올리기,막대 잡고 대각선으로 팔 들어올리기,유연성,0AUDLJ08S_00615.mp4
49,0AUDLJ08S_00342.mp4,수건 잡고 팔 들어올리기,수건 잡고 팔 들어올리기,유연성,0AUDLJ08S_00618.mp4
50,0AUDLJ08S_00346.mp4,탄력밴드 당기면서 팔 들어올리기,탄력밴드 당기면서 팔 들어올리기,유연성,0AUDLJ08S_00622.mp4
51,0AUDLJ08S_00347.mp4,수건 이용하여 장딴지 늘리기,수건 이용하여 장딴지 늘리기,유연성,0AUDLJ08S_00623.mp4
52,0AUDLJ08S_00348.mp4,수동적 관절가동범위 운동,수동적 관절가동범위 운동,유연성,0AUDLJ08S_00624.mp4

In [423]:
# 현재 필터링이 완료된 API 1·3 영상을 통합하여 최종 후보 395개를 고정

api1_video["source_api"] = "API 1"
api3_video["source_api"] = "API 3"

workout_videos = pd.concat(
    [api1_video, api3_video],
    ignore_index=True,
    sort=False
)

print("전체 영상 수:", len(workout_videos))
print("고유 영상 수:", workout_videos["file_nm"].nunique())

display(
    workout_videos["source_api"]
    .value_counts()
    .rename_axis("source_api")
    .reset_index(name="영상 수")
)

전체 영상 수: 395
고유 영상 수: 395

  source_api  영상 수
0      API 1   283
1      API 3   112

In [424]:
# API 1의 체력요인명을 기존 최종 CSV의 6개 체력요인 가중치로 변환하기 위한 매핑 정의

factor_mapping = {
    "근력": {
        "strength": 1.0
    },
    "근력/근지구력": {
        "strength": 0.5,
        "muscularEndurance": 0.5
    },
    "심폐지구력": {
        "cardiovascularEndurance": 1.0
    },
    "전신지구력": {
        "cardiovascularEndurance": 1.0
    },
    "유산소": {
        "cardiovascularEndurance": 1.0
    },
    "유연성": {
        "flexibility": 1.0
    },
    "민첩성": {
        "agility": 1.0
    },
    "민첩성/순발력": {
        "agility": 0.5,
        "power": 0.5
    },
    "순발력": {
        "power": 1.0
    }
}

factor_cols = [
    "strength",
    "muscularEndurance",
    "cardiovascularEndurance",
    "flexibility",
    "agility",
    "power"
]

print("체력요인 매핑:")
for factor, weights in factor_mapping.items():
    print(f"{factor}: {weights}")

체력요인 매핑:
근력: {'strength': 1.0}
근력/근지구력: {'strength': 0.5, 'muscularEndurance': 0.5}
심폐지구력: {'cardiovascularEndurance': 1.0}
전신지구력: {'cardiovascularEndurance': 1.0}
유산소: {'cardiovascularEndurance': 1.0}
유연성: {'flexibility': 1.0}
민첩성: {'agility': 1.0}
민첩성/순발력: {'agility': 0.5, 'power': 0.5}
순발력: {'power': 1.0}

In [425]:
# 현재 API 1 후보 283개의 체력요인 분포와 6개 체력요인 매핑에서 처리되지 않는 값을 확인

api1_factor_check = (
    api1_video["ftns_fctr_nm"]
    .fillna("")
    .str.split("|")
    .explode()
    .str.strip()
)

api1_factor_check = api1_factor_check[
    api1_factor_check != ""
]

factor_distribution = (
    api1_factor_check
    .value_counts()
    .rename_axis("ftns_fctr_nm")
    .reset_index(name="영상 등장 횟수")
)

factor_distribution["mapping_status"] = (
    factor_distribution["ftns_fctr_nm"]
    .apply(
        lambda x: "매핑 가능"
        if x in factor_mapping
        else "매핑 필요"
    )
)

display(factor_distribution)

unmapped_factors = sorted(
    set(api1_factor_check.unique())
    - set(factor_mapping.keys())
)

print("매핑되지 않은 체력요인:", unmapped_factors)

   ftns_fctr_nm  영상 등장 횟수 mapping_status
0           유연성       121          매핑 가능
1            근력        56          매핑 가능
2       근력/근지구력        37          매핑 가능
3           순발력        22          매핑 가능
4           협응성        17          매핑 필요
5       민첩성/순발력        13          매핑 가능
6           민첩성        11          매핑 가능
7         전신지구력         2          매핑 가능
8         심폐지구력         2          매핑 가능
9        민첩성/성능         1          매핑 필요
10          유산소         1          매핑 가능

매핑되지 않은 체력요인: ['민첩성/성능', '협응성']

In [426]:
# API 1의 체력요인을 6개 체력요인 가중치로 변환하고 영상별 합이 1이 되도록 정규화

def calculate_factor_weights(factor_text):
    weights = {col: 0.0 for col in factor_cols}

    if pd.isna(factor_text) or factor_text == "":
        return pd.Series(weights)

    factors = [
        factor.strip()
        for factor in str(factor_text).split("|")
        if factor.strip()
    ]

    # 매핑되지 않은 체력요인이 하나라도 있으면 일단 계산하지 않음
    if any(factor not in factor_mapping for factor in factors):
        return pd.Series({col: None for col in factor_cols})

    for factor in factors:
        for col, value in factor_mapping[factor].items():
            weights[col] += value

    total = sum(weights.values())

    if total > 0:
        weights = {
            col: value / total
            for col, value in weights.items()
        }

    return pd.Series(weights)


api1_factor_weights = (
    api1_video["ftns_fctr_nm"]
    .apply(calculate_factor_weights)
)

api1_factor_result = pd.concat(
    [
        api1_video[["file_nm", "vdo_ttl_nm", "ftns_fctr_nm"]].reset_index(drop=True),
        api1_factor_weights.reset_index(drop=True)
    ],
    axis=1
)

print("API 1 전체 영상:", len(api1_factor_result))

print(
    "6요인 계산 완료:",
    api1_factor_result[factor_cols]
    .notna()
    .all(axis=1)
    .sum()
)

print(
    "추가 처리 필요:",
    api1_factor_result[factor_cols]
    .isna()
    .any(axis=1)
    .sum()
)

display(
    api1_factor_result[
        api1_factor_result[factor_cols]
        .isna()
        .any(axis=1)
    ][
        ["file_nm", "vdo_ttl_nm", "ftns_fctr_nm"]
    ]
)

API 1 전체 영상: 283
6요인 계산 완료: 265
추가 처리 필요: 18

                 file_nm           vdo_ttl_nm ftns_fctr_nm
68   0AUDLJ08S_00574.mp4        사다리 옆으로 발 옮기기       민첩성/성능
157  0AUDLJ08S_00856.mp4          머리 위로 볼 돌리기          협응성
158  0AUDLJ08S_00857.mp4         볼 잡고 몸통 기울이기          협응성
159  0AUDLJ08S_00858.mp4          허리 감아 볼 돌리기          협응성
160  0AUDLJ08S_00859.mp4       메디신 볼 잡고 팔굽혀펴기          협응성
161  0AUDLJ08S_00861.mp4        종아리 사이 감아 돌리기          협응성
162  0AUDLJ08S_00862.mp4  메디신 볼 잡고 런지하며 상체비틀기          협응성
163  0AUDLJ08S_00863.mp4            볼 잡고 점프하기          협응성
164  0AUDLJ08S_00865.mp4            양발 교차 올리기          협응성
165  0AUDLJ08S_00866.mp4         누워 무릎 교차 올리기          협응성
166  0AUDLJ08S_00867.mp4          짐볼 전완대고 버티기          협응성
167  0AUDLJ08S_00868.mp4         짐볼 배에 대고 버티기          협응성
168  0AUDLJ08S_00869.mp4            짐볼 윗몸일으키기          협응성
169  0AUDLJ08S_00870.mp4         다리 교대로 들어올리기          협응성
170  0AUDLJ08S_00871.mp4           양손 모아 균형잡기          협응성
171  0AUDLJ08S_00872.mp4               백 슬라이드          협응성
276  0AUDLJ08S_01001.mp4         협응성운동 루틴프로그램          협응성
282  0AUDLJ08S_01008.mp4       협응성운동 루틴프로그램-1          협응성

In [427]:
# 현재 API 3 후보 112개의 운동명을 API 1의 운동명-체력요인 정보와 매칭하여 영상별 매칭 가능 여부를 확인

api3_current = api3[
    api3["file_nm"].isin(api3_video["file_nm"])
].copy()

api1_exercise_factor = (
    api1[
        ["trng_nm", "ftns_fctr_nm"]
    ]
    .dropna(subset=["trng_nm", "ftns_fctr_nm"])
    .drop_duplicates()
    .copy()
)

# 동일 운동명이 여러 체력요인으로 분류된 경우를 확인
api1_exercise_factor_count = (
    api1_exercise_factor
    .groupby("trng_nm")["ftns_fctr_nm"]
    .nunique()
)

# 체력요인이 하나로 일관된 운동명만 매칭 기준으로 사용
stable_exercise_names = (
    api1_exercise_factor_count[
        api1_exercise_factor_count == 1
    ]
    .index
)

api1_stable_factor = (
    api1_exercise_factor[
        api1_exercise_factor["trng_nm"].isin(stable_exercise_names)
    ]
    .drop_duplicates(subset=["trng_nm"])
    .set_index("trng_nm")["ftns_fctr_nm"]
)

api3_current["matched_factor"] = (
    api3_current["trng_nm"]
    .map(api1_stable_factor)
)

# 영상별 구성 운동 수와 체력요인 매칭 여부를 확인
api3_match_check = (
    api3_current
    .groupby("file_nm")
    .agg(
        exercise_count=("trng_nm", "nunique"),
        matched_exercise_count=(
            "matched_factor",
            lambda x: x.notna().groupby(
                api3_current.loc[x.index, "trng_nm"]
            ).max().sum()
        )
    )
    .reset_index()
)

api3_match_check["all_matched"] = (
    api3_match_check["exercise_count"]
    == api3_match_check["matched_exercise_count"]
)

print("API 3 후보 영상:", len(api3_match_check))
print("모든 운동 매칭:", api3_match_check["all_matched"].sum())
print("일부/미매칭:", (~api3_match_check["all_matched"]).sum())

API 3 후보 영상: 112
모든 운동 매칭: 63
일부/미매칭: 49

In [428]:
# 모든 구성 운동이 매칭된 API 3 영상 63개의 체력요인을 6개 가중치로 변환

api3_matched_file_nm = set(
    api3_match_check.loc[
        api3_match_check["all_matched"],
        "file_nm"
    ]
)

api3_factor_source = api3_current[
    api3_current["file_nm"].isin(api3_matched_file_nm)
][
    ["file_nm", "trng_nm", "matched_factor"]
].drop_duplicates()


def calculate_api3_video_weights(group):
    weights = {col: 0.0 for col in factor_cols}

    # 영상 안의 고유 운동별 체력요인을 한 번씩 반영
    for factor in group["matched_factor"]:
        if factor not in factor_mapping:
            continue

        for col, value in factor_mapping[factor].items():
            weights[col] += value

    total = sum(weights.values())

    if total > 0:
        weights = {
            col: value / total
            for col, value in weights.items()
        }

    return pd.Series(weights)


api3_factor_weights = (
    api3_factor_source
    .groupby("file_nm")
    .apply(calculate_api3_video_weights)
    .reset_index()
)

print("API 3 가중치 계산 영상:", len(api3_factor_weights))

print(
    "가중치 합이 1인 영상:",
    api3_factor_weights[factor_cols]
    .sum(axis=1)
    .round(10)
    .eq(1.0)
    .sum()
)

display(api3_factor_weights.head(10))

API 3 가중치 계산 영상: 63
가중치 합이 1인 영상: 60

/var/folders/vs/vhs7p1q54bd5l01vpxts6spc0000gn/T/ipykernel_92551/235836905.py:42: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(calculate_api3_video_weights)

,file_nm,strength,muscularEndurance,cardiovascularEndurance,flexibility,agility,power
0,0AUDLJ08S_00231.mp4,1.0,0.0,0.0,0.0,0.0,0.0
1,0AUDLJ08S_00233.mp4,1.0,0.0,0.0,0.0,0.0,0.0
2,0AUDLJ08S_00236.mp4,1.0,0.0,0.0,0.0,0.0,0.0
3,0AUDLJ08S_00237.mp4,1.0,0.0,0.0,0.0,0.0,0.0
4,0AUDLJ08S_00238.mp4,1.0,0.0,0.0,0.0,0.0,0.0
5,0AUDLJ08S_00239.mp4,1.0,0.0,0.0,0.0,0.0,0.0
6,0AUDLJ08S_00240.mp4,1.0,0.0,0.0,0.0,0.0,0.0
7,0AUDLJ08S_00242.mp4,1.0,0.0,0.0,0.0,0.0,0.0
8,0AUDLJ08S_00243.mp4,1.0,0.0,0.0,0.0,0.0,0.0
9,0AUDLJ08S_00245.mp4,1.0,0.0,0.0,0.0,0.0,0.0

In [429]:
# API 3에서 체력요인 매칭은 완료됐지만 6개 가중치 합이 1이 되지 않은 영상의 원인을 확인

api3_factor_weights["weight_sum"] = (
    api3_factor_weights[factor_cols]
    .sum(axis=1)
)

api3_invalid_weights = api3_factor_weights[
    ~api3_factor_weights["weight_sum"]
    .round(10)
    .eq(1.0)
].copy()

api3_invalid_detail = (
    api3_factor_source[
        api3_factor_source["file_nm"].isin(
            api3_invalid_weights["file_nm"]
        )
    ]
    .merge(
        api3_video[
            ["file_nm", "vdo_ttl_nm"]
        ],
        on="file_nm",
        how="left"
    )
)

print("가중치 합이 1이 아닌 영상:", len(api3_invalid_weights))

display(
    api3_invalid_weights[
        ["file_nm", "weight_sum"] + factor_cols
    ]
)

display(
    api3_invalid_detail[
        [
            "file_nm",
            "vdo_ttl_nm",
            "trng_nm",
            "matched_factor"
        ]
    ]
    .drop_duplicates()
    .sort_values(["file_nm", "trng_nm"])
)

가중치 합이 1이 아닌 영상: 3

,file_nm,weight_sum,strength,muscularEndurance,cardiovascularEndurance,flexibility,agility,power
19,0AUDLJ08S_00260.mp4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0AUDLJ08S_00262.mp4,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,0AUDLJ08S_00285.mp4,0.0,0.0,0.0,0.0,0.0,0.0,0.0

               file_nm          vdo_ttl_nm           trng_nm matched_factor
0  0AUDLJ08S_00260.mp4           양발 나란히 서기         양발 나란히 서기            평형성
1  0AUDLJ08S_00262.mp4               한발 들기             한발 들기            평형성
6  0AUDLJ08S_00285.mp4  탄력밴드 걸고 서기 루틴 프로그램     탄력밴드 무릎으로 당기기            평형성
2  0AUDLJ08S_00285.mp4  탄력밴드 걸고 서기 루틴 프로그램     탄력밴드 전방으로 당기기            평형성
4  0AUDLJ08S_00285.mp4  탄력밴드 걸고 서기 루틴 프로그램     탄력밴드 측면으로 당기기            평형성
5  0AUDLJ08S_00285.mp4  탄력밴드 걸고 서기 루틴 프로그램  탄력밴드 후방 측면으로 당기기            평형성
3  0AUDLJ08S_00285.mp4  탄력밴드 걸고 서기 루틴 프로그램     탄력밴드 후방으로 당기기            평형성

In [430]:
# 6개 체력요인 가중치 합이 1인 API 3 영상만 최종 체력요인 계산 결과로 확정

api3_factor_weights = api3_factor_weights[
    api3_factor_weights["weight_sum"]
    .round(10)
    .eq(1.0)
].copy()

api3_factor_weights = api3_factor_weights.drop(
    columns=["weight_sum"]
)

print("API 1 체력요인 확정:", 265)
print("API 3 체력요인 확정:", len(api3_factor_weights))
print("현재 총 확정 영상:", 265 + len(api3_factor_weights))

API 1 체력요인 확정: 265
API 3 체력요인 확정: 60
현재 총 확정 영상: 325

In [431]:
# 체력요인이 확정되지 않은 나머지 70개 영상을 API별로 추출하여 확인

confirmed_file_nm = set(
    api1_factor_result.loc[
        api1_factor_result[factor_cols].notna().all(axis=1),
        "file_nm"
    ]
) | set(
    api3_factor_weights["file_nm"]
)

unresolved_videos = workout_videos[
    ~workout_videos["file_nm"].isin(confirmed_file_nm)
].copy()

print("전체 후보 영상:", len(workout_videos))
print("체력요인 확정:", len(confirmed_file_nm))
print("미확정 영상:", len(unresolved_videos))

print("\nAPI별 미확정 영상:")
print(
    unresolved_videos["source_api"]
    .value_counts()
)

display(
    unresolved_videos[
        [
            "source_api",
            "file_nm",
            "vdo_ttl_nm",
            "trng_nm",
            "ftns_fctr_nm"
        ]
    ].sort_values(
        ["source_api", "file_nm"]
    )
)

전체 후보 영상: 395
체력요인 확정: 325
미확정 영상: 70

API별 미확정 영상:
source_api
API 3    52
API 1    18
Name: count, dtype: int64

,source_api,file_nm,vdo_ttl_nm,trng_nm,ftns_fctr_nm
68,API 1,0AUDLJ08S_00574.mp4,사다리 옆으로 발 옮기기,사다리 옆으로 발 옮기기,민첩성/성능
157,API 1,0AUDLJ08S_00856.mp4,머리 위로 볼 돌리기,머리 위로 볼 돌리기,협응성
158,API 1,0AUDLJ08S_00857.mp4,볼 잡고 몸통 기울이기,볼 잡고 몸통 기울이기,협응성
159,API 1,0AUDLJ08S_00858.mp4,허리 감아 볼 돌리기,허리 감아 볼 돌리기,협응성
160,API 1,0AUDLJ08S_00859.mp4,메디신 볼 잡고 팔굽혀펴기,메디신 볼 잡고 팔 굽혀 펴기,협응성
...,...,...,...,...,...
386,API 3,0AUDLJ08S_00343.mp4,등척성운동-벌림,벌림,NaN
387,API 3,0AUDLJ08S_00344.mp4,등척성운동-바깥돌림,바깥돌림,NaN
388,API 3,0AUDLJ08S_00345.mp4,등척성운동-안쪽 돌림,안쪽 돌림,NaN
393,API 3,0AUDLJ08S_00350.mp4,어깨 안쪽 돌림,어깨 안쪽 돌림,NaN
394,API 3,0AUDLJ08S_01017.mp4,테니스공을 활용한 뭉친근육 완화 운동,가슴|전완(내측)|목 상부|허벅지(햄스트링)|종아리(기본)|정강이|허리|목 외측|전...,NaN

In [432]:
# 미확정 API 3 영상 52개를 평형성·일부 매칭·전체 미매칭 유형으로 분류

api3_unresolved_file_nm = set(
    unresolved_videos.loc[
        unresolved_videos["source_api"] == "API 3",
        "file_nm"
    ]
)

api3_unresolved_detail = api3_current[
    api3_current["file_nm"].isin(api3_unresolved_file_nm)
].copy()

api3_unresolved_detail["six_factor_mappable"] = (
    api3_unresolved_detail["matched_factor"]
    .isin(factor_mapping.keys())
)

api3_unresolved_summary = (
    api3_unresolved_detail
    .groupby("file_nm")
    .agg(
        exercise_count=("trng_nm", "nunique"),
        matched_count=("matched_factor", lambda x: x.notna().sum()),
        six_factor_count=("six_factor_mappable", "sum"),
        matched_factors=(
            "matched_factor",
            lambda x: "|".join(
                sorted(set(x.dropna().astype(str)))
            )
        )
    )
    .reset_index()
)

def classify_unresolved(row):
    if (
        row["matched_count"] > 0
        and row["six_factor_count"] == 0
    ):
        return "6요인 외 체력요인"

    if row["six_factor_count"] == 0:
        return "전체 미매칭"

    if row["six_factor_count"] < row["exercise_count"]:
        return "일부 매칭"

    return "기타"


api3_unresolved_summary["unresolved_type"] = (
    api3_unresolved_summary.apply(
        classify_unresolved,
        axis=1
    )
)

print(
    api3_unresolved_summary["unresolved_type"]
    .value_counts()
)

display(
    api3_unresolved_summary[
        [
            "file_nm",
            "exercise_count",
            "matched_count",
            "six_factor_count",
            "matched_factors",
            "unresolved_type"
        ]
    ]
)

unresolved_type
전체 미매칭        44
6요인 외 체력요인     4
기타             4
Name: count, dtype: int64

,file_nm,exercise_count,matched_count,six_factor_count,matched_factors,unresolved_type
0,0AUDLJ08S_00185.mp4,2,0,0,,전체 미매칭
1,0AUDLJ08S_00188.mp4,1,0,0,,전체 미매칭
2,0AUDLJ08S_00189.mp4,1,0,0,,전체 미매칭
3,0AUDLJ08S_00232.mp4,1,0,0,,전체 미매칭
4,0AUDLJ08S_00234.mp4,1,0,0,,전체 미매칭
5,0AUDLJ08S_00235.mp4,1,0,0,,전체 미매칭
6,0AUDLJ08S_00241.mp4,1,0,0,,전체 미매칭
7,0AUDLJ08S_00244.mp4,1,0,0,,전체 미매칭
8,0AUDLJ08S_00248.mp4,1,0,0,,전체 미매칭
9,0AUDLJ08S_00249.mp4,1,0,0,,전체 미매칭
10,0AUDLJ08S_00250.mp4,1,0,0,,전체 미매칭
11,0AUDLJ08S_00258.mp4,1,0,0,,전체 미매칭
12,0AUDLJ08S_00259.mp4,1,0,0,,전체 미매칭
13,0AUDLJ08S_00260.mp4,1,4,0,평형성,6요인 외 체력요인
14,0AUDLJ08S_00261.mp4,1,0,0,,전체 미매칭
15,0AUDLJ08S_00262.mp4,1,5,0,평형성,6요인 외 체력요인
16,0AUDLJ08S_00268.mp4,1,0,0,,전체 미매칭
17,0AUDLJ08S_00269.mp4,1,0,0,,전체 미매칭
18,0AUDLJ08S_00272.mp4,1,0,0,,전체 미매칭
19,0AUDLJ08S_00274.mp4,4,1,0,평형성,6요인 외 체력요인
20,0AUDLJ08S_00277.mp4,3,0,0,,전체 미매칭
21,0AUDLJ08S_00279.mp4,2,0,0,,전체 미매칭
22,0AUDLJ08S_00280.mp4,1,0,0,,전체 미매칭
23,0AUDLJ08S_00281.mp4,2,0,0,,전체 미매칭
24,0AUDLJ08S_00282.mp4,2,3,3,근력,기타
25,0AUDLJ08S_00285.mp4,5,26,0,평형성,6요인 외 체력요인
26,0AUDLJ08S_00289.mp4,1,0,0,,전체 미매칭
27,0AUDLJ08S_00290.mp4,1,0,0,,전체 미매칭
28,0AUDLJ08S_00293.mp4,2,0,0,,전체 미매칭
29,0AUDLJ08S_00295.mp4,3,9,9,근력,기타
30,0AUDLJ08S_00296.mp4,1,0,0,,전체 미매칭
31,0AUDLJ08S_00297.mp4,1,0,0,,전체 미매칭
32,0AUDLJ08S_00299.mp4,1,0,0,,전체 미매칭
33,0AUDLJ08S_00300.mp4,3,5,5,근력,기타
34,0AUDLJ08S_00301.mp4,3,4,4,근력,기타
35,0AUDLJ08S_00304.mp4,1,0,0,,전체 미매칭
36,0AUDLJ08S_00306.mp4,1,0,0,,전체 미매칭
37,0AUDLJ08S_00308.mp4,1,0,0,,전체 미매칭
38,0AUDLJ08S_00310.mp4,1,0,0,,전체 미매칭
39,0AUDLJ08S_00314.mp4,1,0,0,,전체 미매칭
40,0AUDLJ08S_00320.mp4,1,0,0,,전체 미매칭
41,0AUDLJ08S_00322.mp4,1,0,0,,전체 미매칭
42,0AUDLJ08S_00331.mp4,1,0,0,,전체 미매칭
43,0AUDLJ08S_00332.mp4,1,0,0,,전체 미매칭
44,0AUDLJ08S_00333.mp4,1,0,0,,전체 미매칭
45,0AUDLJ08S_00334.mp4,1,0,0,,전체 미매칭
46,0AUDLJ08S_00338.mp4,1,0,0,,전체 미매칭
47,0AUDLJ08S_00343.mp4,1,0,0,,전체 미매칭
48,0AUDLJ08S_00344.mp4,1,0,0,,전체 미매칭
49,0AUDLJ08S_00345.mp4,1,0,0,,전체 미매칭
50,0AUDLJ08S_00350.mp4,1,0,0,,전체 미매칭
51,0AUDLJ08S_01017.mp4,9,0,0,,전체 미매칭

In [433]:
# API 1과 API 3에서 계산이 완료된 영상별 6개 체력요인 가중치를 하나로 통합

api1_final_weights = api1_factor_result[
    api1_factor_result[factor_cols].notna().all(axis=1)
][
    ["file_nm"] + factor_cols
].copy()

api3_final_weights = api3_factor_weights[
    ["file_nm"] + factor_cols
].copy()

video_factor_weights = pd.concat(
    [api1_final_weights, api3_final_weights],
    ignore_index=True
)

print("체력요인 데이터:", len(video_factor_weights))
print("고유 영상:", video_factor_weights["file_nm"].nunique())

체력요인 데이터: 325
고유 영상: 325

In [434]:
# 최종 체력요인 데이터를 결합하고 실제 영상 URL을 포함한 12개 컬럼으로 정리

workout_videos = (
    workout_videos
    .drop(columns=factor_cols, errors="ignore")
    .merge(
        video_factor_weights,
        on="file_nm",
        how="inner"
    )
)

# 기존 기본 URL은 제거하고 완성된 영상 URL만 file_url로 사용
workout_videos = workout_videos.drop(
    columns=["file_url"],
    errors="ignore"
)

workout_videos = workout_videos.rename(
    columns={
        "vdo_ttl_nm": "title",
        "video_url": "file_url",
        "vdo_len": "video_length",
        "aggrp_nm": "age_group",
        "tool_nm": "equipment"
    }
)

workout_videos = workout_videos[
    [
        "file_nm",
        "title",
        "file_url",
        "video_length",
        "age_group",
        "strength",
        "muscularEndurance",
        "cardiovascularEndurance",
        "flexibility",
        "agility",
        "power",
        "equipment"
    ]
].copy()

print("영상 수:", len(workout_videos))
print("컬럼 수:", len(workout_videos.columns))
print("중복 컬럼:", workout_videos.columns.duplicated().sum())

영상 수: 325
컬럼 수: 12
중복 컬럼: 0

In [435]:
# 제목이 정확히 '걷기'인 영상만 최종 추천 후보에서 제외

workout_videos = workout_videos[
    workout_videos["title"].str.strip() != "걷기"
].reset_index(drop=True)

print("최종 영상 수:", len(workout_videos))
print("고유 영상 수:", workout_videos["file_nm"].nunique())
print("걷기 영상 잔존:", (workout_videos["title"].str.strip() == "걷기").sum())

최종 영상 수: 324
고유 영상 수: 324
걷기 영상 잔존: 0

In [436]:
# 최종 324개 영상에서 각 체력요인이 0보다 큰 영상의 개수를 확인

factor_video_counts = (
    (workout_videos[factor_cols] > 0)
    .sum()
    .sort_values(ascending=False)
)

factor_video_counts.index = [
    {
        "strength": "근력",
        "muscularEndurance": "근지구력",
        "cardiovascularEndurance": "심폐지구력",
        "flexibility": "유연성",
        "agility": "민첩성",
        "power": "순발력"
    }[col]
    for col in factor_video_counts.index
]

print("최종 영상 수:", len(workout_videos))
print("\n체력요인별 포함 영상 수:")
print(factor_video_counts)

최종 영상 수: 324

체력요인별 포함 영상 수:
근력       136
유연성      133
순발력       40
근지구력      37
민첩성       29
심폐지구력      4
dtype: int64

In [437]:
# 현재 최종 데이터에서 URL·루틴 영상·동일 제목 중복·문제 영상이 실제로 존재하는지 한 번에 점검

print("=== 1. 컬럼 ===")
print(workout_videos.columns.tolist())
print("shape:", workout_videos.shape)

print("\n=== 2. 루틴/프로그램 영상 ===")
routine_check = workout_videos[
    workout_videos["title"].str.contains(
        "루틴|프로그램",
        na=False
    )
][["file_nm", "title"]]

print("개수:", len(routine_check))
display(routine_check)

print("\n=== 3. 동일 제목 중복 ===")
duplicate_title_check = (
    workout_videos
    .groupby("title")
    .filter(lambda x: len(x) > 1)
    .sort_values("title")
)

print(
    "중복 제목 그룹:",
    duplicate_title_check["title"].nunique()
)
print(
    "해당 영상 수:",
    len(duplicate_title_check)
)

display(
    duplicate_title_check[
        ["file_nm", "title"]
    ].head(30)
)

print("\n=== 4. 문제 영상 확인 ===")
problem_titles = [
    "하지 루틴 스트레칭2",
    "빠르게 걷기(3단계)",
    "팔굽혀펴기-2",
    "짝 운동",
    "원판 던지기",
    "서서 바벨 위로 밀기"
]

display(
    workout_videos[
        workout_videos["title"].isin(problem_titles)
    ]
)

=== 1. 컬럼 ===
['file_nm', 'title', 'file_url', 'video_length', 'age_group', 'strength', 'muscularEndurance', 'cardiovascularEndurance', 'flexibility', 'agility', 'power', 'equipment']
shape: (324, 12)

=== 2. 루틴/프로그램 영상 ===
개수: 16

                 file_nm                 title
81   0AUDLJ08S_00592.mp4           하지 루틴 스트레칭1
82   0AUDLJ08S_00593.mp4           하지 루틴 스트레칭2
83   0AUDLJ08S_00594.mp4            상지 루틴 스트레칭
84   0AUDLJ08S_00595.mp4            전신 루틴 스트레칭
85   0AUDLJ08S_00596.mp4   유산소 운동 전 동적 루틴 스트레칭
86   0AUDLJ08S_00597.mp4  좌식생활자를 위한 동적 루틴 스트레칭
87   0AUDLJ08S_00598.mp4    짐볼을 이용한 동적 루틴 스트레칭
88   0AUDLJ08S_00599.mp4  작은 공을 이용한 동적 루틴 스트레칭
89   0AUDLJ08S_00600.mp4       자가근막이완술 루틴 스트레칭
257  0AUDLJ08S_00999.mp4          유연성운동 루틴프로그램
258  0AUDLJ08S_01000.mp4      근력·근지구력운동 루틴프로그램
259  0AUDLJ08S_01002.mp4          순발력운동 루틴프로그램
260  0AUDLJ08S_01003.mp4          민첩성운동 루틴프로그램
261  0AUDLJ08S_01004.mp4        유연성운동 루틴프로그램-1
262  0AUDLJ08S_01006.mp4    근력·근지구력운동 루틴프로그램-2
263  0AUDLJ08S_01007.mp4        유연성운동 루틴프로그램-2

=== 3. 동일 제목 중복 ===
중복 제목 그룹: 38
해당 영상 수: 76

                 file_nm                  title
92   0AUDLJ08S_00603.mp4       공에 엎드려서 상체 들어올리기
312  0AUDLJ08S_00329.mp4       공에 엎드려서 상체 들어올리기
275  0AUDLJ08S_00247.mp4  네발기기 자세에서 다리 위로 뻗어올리기
50   0AUDLJ08S_00554.mp4  네발기기 자세에서 다리 위로 뻗어올리기
274  0AUDLJ08S_00246.mp4   네발기기 자세에서 손바닥으로 바닥밀기
44   0AUDLJ08S_00548.mp4   네발기기 자세에서 손바닥으로 바닥밀기
37   0AUDLJ08S_00541.mp4         누워서 공들고 몸 기울이기
301  0AUDLJ08S_00298.mp4         누워서 공들고 몸 기울이기
268  0AUDLJ08S_00238.mp4           누워서 다리 들어올리기
34   0AUDLJ08S_00538.mp4           누워서 다리 들어올리기
100  0AUDLJ08S_00613.mp4      누워서 막대 잡고 팔 들어올리기
316  0AUDLJ08S_00339.mp4      누워서 막대 잡고 팔 들어올리기
101  0AUDLJ08S_00614.mp4       누워서 막대 잡고 팔 회전하기
317  0AUDLJ08S_00340.mp4       누워서 막대 잡고 팔 회전하기
40   0AUDLJ08S_00544.mp4          누워서 엉덩이 들어올리기
272  0AUDLJ08S_00243.mp4          누워서 엉덩이 들어올리기
35   0AUDLJ08S_00539.mp4     누워서 팔 다리 동시에 들어올리기
269  0AUDLJ08S_00239.mp4     누워서 팔 다리 동시에 들어올리기
39   0AUDLJ08S_00543.mp4             누워서 하늘 자전거
271  0AUDLJ08S_00242.mp4             누워서 하늘 자전거
102  0AUDLJ08S_00615.mp4    막대 잡고 대각선으로 팔 들어올리기
318  0AUDLJ08S_00341.mp4    막대 잡고 대각선으로 팔 들어올리기
58   0AUDLJ08S_00564.mp4          무릎 높여 제자리 달리기
308  0AUDLJ08S_00312.mp4          무릎 높여 제자리 달리기
52   0AUDLJ08S_00558.mp4           물병 옆으로 들어올리기
277  0AUDLJ08S_00252.mp4           물병 옆으로 들어올리기
68   0AUDLJ08S_00576.mp4                   버피운동
310  0AUDLJ08S_00315.mp4                   버피운동
14   0AUDLJ08S_00518.mp4             서서 상체 일으키기
264  0AUDLJ08S_00231.mp4             서서 상체 일으키기

=== 4. 문제 영상 확인 ===

,file_nm,title,file_url,video_length,age_group,strength,muscularEndurance,cardiovascularEndurance,flexibility,agility,power,equipment
2,0AUDLJ08S_00491.mp4,원판 던지기,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,67,공통,1.0,0.0,0.0,0.0,0.0,0.0,원판
5,0AUDLJ08S_00504.mp4,서서 바벨 위로 밀기,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,67,공통,1.0,0.0,0.0,0.0,0.0,0.0,바벨|덤벨
82,0AUDLJ08S_00593.mp4,하지 루틴 스트레칭2,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,90,공통,0.0,0.0,1.0,0.0,0.0,0.0,매트
90,0AUDLJ08S_00601.mp4,빠르게 걷기(3단계),http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,48,공통,0.0,0.0,0.0,1.0,0.0,0.0,
91,0AUDLJ08S_00602.mp4,팔굽혀펴기-2,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,50,공통,0.0,0.0,0.0,1.0,0.0,0.0,매트
306,0AUDLJ08S_00309.mp4,짝 운동,http://openapi.kspo.or.kr/web/video/0AUDLJ08S_...,68,공통,1.0,0.0,0.0,0.0,0.0,0.0,보슈

In [438]:
# 확정된 루틴·프로그램 16개와 원판 던지기, 짝 운동, 빠르게 걷기(3단계)를 추천 후보에서 제거

remove_file_nm = [
    # 루틴·프로그램 16개
    "0AUDLJ08S_00592.mp4",
    "0AUDLJ08S_00593.mp4",
    "0AUDLJ08S_00594.mp4",
    "0AUDLJ08S_00595.mp4",
    "0AUDLJ08S_00596.mp4",
    "0AUDLJ08S_00597.mp4",
    "0AUDLJ08S_00598.mp4",
    "0AUDLJ08S_00599.mp4",
    "0AUDLJ08S_00600.mp4",
    "0AUDLJ08S_00999.mp4",
    "0AUDLJ08S_01000.mp4",
    "0AUDLJ08S_01002.mp4",
    "0AUDLJ08S_01003.mp4",
    "0AUDLJ08S_01004.mp4",
    "0AUDLJ08S_01006.mp4",
    "0AUDLJ08S_01007.mp4",

    # 개별 제외 영상
    "0AUDLJ08S_00491.mp4",  # 원판 던지기
    "0AUDLJ08S_00309.mp4",  # 짝 운동
    "0AUDLJ08S_00601.mp4"   # 빠르게 걷기(3단계)
]

workout_videos = workout_videos[
    ~workout_videos["file_nm"].isin(remove_file_nm)
].reset_index(drop=True)

print("최종 영상 수:", len(workout_videos))
print("제거 대상 잔존:", workout_videos["file_nm"].isin(remove_file_nm).sum())

최종 영상 수: 305
제거 대상 잔존: 0

In [439]:
# 현재 305개 영상에서 제목이 동일한 중복 운동 38개 그룹을 전체 확인

duplicate_title_check = (
    workout_videos[
        workout_videos.duplicated("title", keep=False)
    ]
    .sort_values(["title", "file_nm"])
    [
        [
            "file_nm",
            "title",
            "video_length",
            "age_group",
            "strength",
            "muscularEndurance",
            "cardiovascularEndurance",
            "flexibility",
            "agility",
            "power",
            "equipment"
        ]
    ]
)

print("중복 제목 그룹:", duplicate_title_check["title"].nunique())
print("해당 영상 수:", len(duplicate_title_check))

display(duplicate_title_check)

중복 제목 그룹: 38
해당 영상 수: 76

,file_nm,title,video_length,age_group,strength,muscularEndurance,cardiovascularEndurance,flexibility,agility,power,equipment
293,0AUDLJ08S_00329.mp4,공에 엎드려서 상체 들어올리기,71,공통,0.0,0.0,0.0,1.0,0.0,0.0,짐볼
81,0AUDLJ08S_00603.mp4,공에 엎드려서 상체 들어올리기,60,공통,0.0,0.0,0.0,1.0,0.0,0.0,짐볼
257,0AUDLJ08S_00247.mp4,네발기기 자세에서 다리 위로 뻗어올리기,63,공통,1.0,0.0,0.0,0.0,0.0,0.0,매트
49,0AUDLJ08S_00554.mp4,네발기기 자세에서 다리 위로 뻗어올리기,69,공통,1.0,0.0,0.0,0.0,0.0,0.0,밴드
256,0AUDLJ08S_00246.mp4,네발기기 자세에서 손바닥으로 바닥밀기,65,공통,1.0,0.0,0.0,0.0,0.0,0.0,매트
...,...,...,...,...,...,...,...,...,...,...,...
52,0AUDLJ08S_00559.mp4,팔꿈치 굽히기,71,공통,1.0,0.0,0.0,0.0,0.0,0.0,물병|밴드
269,0AUDLJ08S_00270.mp4,한발 서서 균형잡기,64,공통,1.0,0.0,0.0,0.0,0.0,0.0,의자
24,0AUDLJ08S_00529.mp4,한발 서서 균형잡기,59,공통,1.0,0.0,0.0,0.0,0.0,0.0,의자
258,0AUDLJ08S_00251.mp4,허리 굽혀 팔 뒤로 들기,66,공통,1.0,0.0,0.0,0.0,0.0,0.0,물병(밴드)
50,0AUDLJ08S_00557.mp4,허리 굽혀 팔 뒤로 들기,77,공통,1.0,0.0,0.0,0.0,0.0,0.0,물병|밴드

In [440]:
# 동일 제목 영상 38쌍의 파일명·도구·영상길이·체력요인을 나란히 비교

duplicate_compare = (
    workout_videos[
        workout_videos.duplicated("title", keep=False)
    ]
    .sort_values(["title", "file_nm"])
    .groupby("title")
    .agg({
        "file_nm": " | ".join,
        "equipment": lambda x: " | ".join(x.fillna("").astype(str)),
        "video_length": lambda x: " | ".join(x.astype(str)),
        "strength": lambda x: " | ".join(x.astype(str)),
        "muscularEndurance": lambda x: " | ".join(x.astype(str)),
        "cardiovascularEndurance": lambda x: " | ".join(x.astype(str)),
        "flexibility": lambda x: " | ".join(x.astype(str)),
        "agility": lambda x: " | ".join(x.astype(str)),
        "power": lambda x: " | ".join(x.astype(str))
    })
    .reset_index()
)

display(duplicate_compare)

,title,file_nm,equipment,video_length,strength,muscularEndurance,cardiovascularEndurance,flexibility,agility,power
0,공에 엎드려서 상체 들어올리기,0AUDLJ08S_00329.mp4 | 0AUDLJ08S_00603.mp4,짐볼 | 짐볼,71 | 60,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0
1,네발기기 자세에서 다리 위로 뻗어올리기,0AUDLJ08S_00247.mp4 | 0AUDLJ08S_00554.mp4,매트 | 밴드,63 | 69,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
2,네발기기 자세에서 손바닥으로 바닥밀기,0AUDLJ08S_00246.mp4 | 0AUDLJ08S_00548.mp4,매트 | 매트,65 | 57,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
3,누워서 공들고 몸 기울이기,0AUDLJ08S_00298.mp4 | 0AUDLJ08S_00541.mp4,공 | 공,68 | 83,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
4,누워서 다리 들어올리기,0AUDLJ08S_00238.mp4 | 0AUDLJ08S_00538.mp4,매트|테이블 | 매트,51 | 72,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
5,누워서 막대 잡고 팔 들어올리기,0AUDLJ08S_00339.mp4 | 0AUDLJ08S_00613.mp4,막대 | 막대,73 | 57,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0
6,누워서 막대 잡고 팔 회전하기,0AUDLJ08S_00340.mp4 | 0AUDLJ08S_00614.mp4,막대 | 막대,64 | 57,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0
7,누워서 엉덩이 들어올리기,0AUDLJ08S_00243.mp4 | 0AUDLJ08S_00544.mp4,매트|소파|짐볼 | 매트|의자|짐볼,67 | 65,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
8,누워서 팔 다리 동시에 들어올리기,0AUDLJ08S_00239.mp4 | 0AUDLJ08S_00539.mp4,| 매트|공,58 | 69,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
9,누워서 하늘 자전거,0AUDLJ08S_00242.mp4 | 0AUDLJ08S_00543.mp4,소파 | 소파,56 | 63,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
10,막대 잡고 대각선으로 팔 들어올리기,0AUDLJ08S_00341.mp4 | 0AUDLJ08S_00615.mp4,막대 | 막대,82 | 57,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0
11,무릎 높여 제자리 달리기,0AUDLJ08S_00312.mp4 | 0AUDLJ08S_00564.mp4,|,49 | 61,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.5 | 0.5,0.5 | 0.5
12,물병 옆으로 들어올리기,0AUDLJ08S_00252.mp4 | 0AUDLJ08S_00558.mp4,물병 | 물병,49 | 62,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
13,버피운동,0AUDLJ08S_00315.mp4 | 0AUDLJ08S_00576.mp4,|,47 | 68,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.5 | 0.5,0.5 | 0.5
14,서서 상체 일으키기,0AUDLJ08S_00231.mp4 | 0AUDLJ08S_00518.mp4,덤벨|물병|밴드 | 물병|밴드,82 | 66,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
15,수건 이용하여 장딴지 늘리기,0AUDLJ08S_00347.mp4 | 0AUDLJ08S_00623.mp4,수건 | 수건,61 | 61,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0
16,수건 잡고 팔 들어올리기,0AUDLJ08S_00342.mp4 | 0AUDLJ08S_00618.mp4,수건 | 수건,69 | 57,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0
17,수동적 관절가동범위 운동,0AUDLJ08S_00348.mp4 | 0AUDLJ08S_00624.mp4,의자 | 의자,78 | 61,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0
18,앉아서 엉덩관절 굽히기,0AUDLJ08S_00267.mp4 | 0AUDLJ08S_00524.mp4,의자 | 의자|짐볼|소파,59 | 68,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
19,앉았다 일어서면서 점프하기,0AUDLJ08S_00311.mp4 | 0AUDLJ08S_00563.mp4,|,34 | 59,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.5 | 0.5,0.5 | 0.5
20,엎드려 버티기,0AUDLJ08S_00236.mp4 | 0AUDLJ08S_00536.mp4,매트 | 매트,58 | 71,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
21,엎드려서 균형잡기,0AUDLJ08S_00305.mp4 | 0AUDLJ08S_00513.mp4,보슈 | 보슈,82 | 92,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
22,엎드려서 다리 차올리기,0AUDLJ08S_00307.mp4 | 0AUDLJ08S_00515.mp4,보슈 | 보슈,51 | 76,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
23,엎드려서 팔 다리 들기,0AUDLJ08S_00245.mp4 | 0AUDLJ08S_00547.mp4,매트 | 매트,73 | 91,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
24,옆으로 누워 버티기,0AUDLJ08S_00237.mp4 | 0AUDLJ08S_00537.mp4,매트 | 매트,40 | 62,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
25,옆으로 누워서 팔 앞으로 당기기,0AUDLJ08S_00335.mp4 | 0AUDLJ08S_00609.mp4,베개 | 베개,62 | 57,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0
26,옆으로 펀치하기,0AUDLJ08S_00313.mp4 | 0AUDLJ08S_00565.mp4,덤벨 | 덤벨,54 | 47,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.5 | 0.5,0.5 | 0.5
27,의자 앞에서 앉았다 일어서기,0AUDLJ08S_00264.mp4 | 0AUDLJ08S_00520.mp4,의자 | 의자,67 | 62,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
28,의자에 앉아 다리 뻗어 올리기,0AUDLJ08S_00266.mp4 | 0AUDLJ08S_00523.mp4,의자|매트 | 의자|매트,59 | 70,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
29,의자에 한 다리 올리고 앉았다 일어서기,0AUDLJ08S_00265.mp4 | 0AUDLJ08S_00522.mp4,의자|테이블 | 의자,58 | 57,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
30,점프 팔굽혀펴기,0AUDLJ08S_00316.mp4 | 0AUDLJ08S_00577.mp4,|,45 | 56,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.5 | 0.5,0.5 | 0.5
31,짐볼에 엎드려서 팔 다리 들기,0AUDLJ08S_00288.mp4 | 0AUDLJ08S_00549.mp4,짐볼 | 짐볼,52 | 69,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
32,탄력밴드 당기면서 팔 들어올리기,0AUDLJ08S_00346.mp4 | 0AUDLJ08S_00622.mp4,밴드 | 밴드,67 | 62,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0
33,탄력밴드 어깨 가쪽 돌림,0AUDLJ08S_00278.mp4 | 0AUDLJ08S_00551.mp4,밴드 | 밴드,63 | 67,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
34,테이블 이용하여 팔 옆으로 벌리기,0AUDLJ08S_00337.mp4 | 0AUDLJ08S_00611.mp4,테이블 | 테이블,55 | 57,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0
35,팔꿈치 굽히기,0AUDLJ08S_00253.mp4 | 0AUDLJ08S_00559.mp4,물병|밴드 | 물병|밴드,58 | 71,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
36,한발 서서 균형잡기,0AUDLJ08S_00270.mp4 | 0AUDLJ08S_00529.mp4,의자 | 의자,64 | 59,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0
37,허리 굽혀 팔 뒤로 들기,0AUDLJ08S_00251.mp4 | 0AUDLJ08S_00557.mp4,물병(밴드) | 물병|밴드,66 | 77,1.0 | 1.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0,0.0 | 0.0

In [441]:
# 운동 제목과 사용 도구가 모두 동일한 실질적 중복 영상만 확인

same_exercise_check = (
    workout_videos[
        workout_videos.duplicated(
            subset=["title", "equipment"],
            keep=False
        )
    ]
    .sort_values(["title", "equipment", "file_nm"])
)

print(
    "제목+도구 동일 그룹:",
    same_exercise_check.groupby(
        ["title", "equipment"],
        dropna=False
    ).ngroups
)

print("해당 영상 수:", len(same_exercise_check))

display(
    same_exercise_check[
        [
            "file_nm",
            "title",
            "equipment",
            "video_length",
            "strength",
            "muscularEndurance",
            "cardiovascularEndurance",
            "flexibility",
            "agility",
            "power"
        ]
    ]
)

제목+도구 동일 그룹: 30
해당 영상 수: 60

,file_nm,title,equipment,video_length,strength,muscularEndurance,cardiovascularEndurance,flexibility,agility,power
293,0AUDLJ08S_00329.mp4,공에 엎드려서 상체 들어올리기,짐볼,71,0.0,0.0,0.0,1.0,0.0,0.0
81,0AUDLJ08S_00603.mp4,공에 엎드려서 상체 들어올리기,짐볼,60,0.0,0.0,0.0,1.0,0.0,0.0
256,0AUDLJ08S_00246.mp4,네발기기 자세에서 손바닥으로 바닥밀기,매트,65,1.0,0.0,0.0,0.0,0.0,0.0
43,0AUDLJ08S_00548.mp4,네발기기 자세에서 손바닥으로 바닥밀기,매트,57,1.0,0.0,0.0,0.0,0.0,0.0
283,0AUDLJ08S_00298.mp4,누워서 공들고 몸 기울이기,공,68,1.0,0.0,0.0,0.0,0.0,0.0
36,0AUDLJ08S_00541.mp4,누워서 공들고 몸 기울이기,공,83,1.0,0.0,0.0,0.0,0.0,0.0
297,0AUDLJ08S_00339.mp4,누워서 막대 잡고 팔 들어올리기,막대,73,0.0,0.0,0.0,1.0,0.0,0.0
89,0AUDLJ08S_00613.mp4,누워서 막대 잡고 팔 들어올리기,막대,57,0.0,0.0,0.0,1.0,0.0,0.0
298,0AUDLJ08S_00340.mp4,누워서 막대 잡고 팔 회전하기,막대,64,0.0,0.0,0.0,1.0,0.0,0.0
90,0AUDLJ08S_00614.mp4,누워서 막대 잡고 팔 회전하기,막대,57,0.0,0.0,0.0,1.0,0.0,0.0
253,0AUDLJ08S_00242.mp4,누워서 하늘 자전거,소파,56,1.0,0.0,0.0,0.0,0.0,0.0
38,0AUDLJ08S_00543.mp4,누워서 하늘 자전거,소파,63,1.0,0.0,0.0,0.0,0.0,0.0
299,0AUDLJ08S_00341.mp4,막대 잡고 대각선으로 팔 들어올리기,막대,82,0.0,0.0,0.0,1.0,0.0,0.0
91,0AUDLJ08S_00615.mp4,막대 잡고 대각선으로 팔 들어올리기,막대,57,0.0,0.0,0.0,1.0,0.0,0.0
289,0AUDLJ08S_00312.mp4,무릎 높여 제자리 달리기,,49,0.0,0.0,0.0,0.0,0.5,0.5
57,0AUDLJ08S_00564.mp4,무릎 높여 제자리 달리기,,61,0.0,0.0,0.0,0.0,0.5,0.5
259,0AUDLJ08S_00252.mp4,물병 옆으로 들어올리기,물병,49,1.0,0.0,0.0,0.0,0.0,0.0
51,0AUDLJ08S_00558.mp4,물병 옆으로 들어올리기,물병,62,1.0,0.0,0.0,0.0,0.0,0.0
291,0AUDLJ08S_00315.mp4,버피운동,,47,0.0,0.0,0.0,0.0,0.5,0.5
67,0AUDLJ08S_00576.mp4,버피운동,,68,0.0,0.0,0.0,0.0,0.5,0.5
302,0AUDLJ08S_00347.mp4,수건 이용하여 장딴지 늘리기,수건,61,0.0,0.0,0.0,1.0,0.0,0.0
99,0AUDLJ08S_00623.mp4,수건 이용하여 장딴지 늘리기,수건,61,0.0,0.0,0.0,1.0,0.0,0.0
300,0AUDLJ08S_00342.mp4,수건 잡고 팔 들어올리기,수건,69,0.0,0.0,0.0,1.0,0.0,0.0
94,0AUDLJ08S_00618.mp4,수건 잡고 팔 들어올리기,수건,57,0.0,0.0,0.0,1.0,0.0,0.0
303,0AUDLJ08S_00348.mp4,수동적 관절가동범위 운동,의자,78,0.0,0.0,0.0,1.0,0.0,0.0
100,0AUDLJ08S_00624.mp4,수동적 관절가동범위 운동,의자,61,0.0,0.0,0.0,1.0,0.0,0.0
288,0AUDLJ08S_00311.mp4,앉았다 일어서면서 점프하기,,34,0.0,0.0,0.0,0.0,0.5,0.5
56,0AUDLJ08S_00563.mp4,앉았다 일어서면서 점프하기,,59,0.0,0.0,0.0,0.0,0.5,0.5
248,0AUDLJ08S_00236.mp4,엎드려 버티기,매트,58,1.0,0.0,0.0,0.0,0.0,0.0
31,0AUDLJ08S_00536.mp4,엎드려 버티기,매트,71,1.0,0.0,0.0,0.0,0.0,0.0
286,0AUDLJ08S_00305.mp4,엎드려서 균형잡기,보슈,82,1.0,0.0,0.0,0.0,0.0,0.0
9,0AUDLJ08S_00513.mp4,엎드려서 균형잡기,보슈,92,1.0,0.0,0.0,0.0,0.0,0.0
287,0AUDLJ08S_00307.mp4,엎드려서 다리 차올리기,보슈,51,1.0,0.0,0.0,0.0,0.0,0.0
11,0AUDLJ08S_00515.mp4,엎드려서 다리 차올리기,보슈,76,1.0,0.0,0.0,0.0,0.0,0.0
255,0AUDLJ08S_00245.mp4,엎드려서 팔 다리 들기,매트,73,1.0,0.0,0.0,0.0,0.0,0.0
42,0AUDLJ08S_00547.mp4,엎드려서 팔 다리 들기,매트,91,1.0,0.0,0.0,0.0,0.0,0.0
249,0AUDLJ08S_00237.mp4,옆으로 누워 버티기,매트,40,1.0,0.0,0.0,0.0,0.0,0.0
32,0AUDLJ08S_00537.mp4,옆으로 누워 버티기,매트,62,1.0,0.0,0.0,0.0,0.0,0.0
294,0AUDLJ08S_00335.mp4,옆으로 누워서 팔 앞으로 당기기,베개,62,0.0,0.0,0.0,1.0,0.0,0.0
86,0AUDLJ08S_00609.mp4,옆으로 누워서 팔 앞으로 당기기,베개,57,0.0,0.0,0.0,1.0,0.0,0.0
290,0AUDLJ08S_00313.mp4,옆으로 펀치하기,덤벨,54,0.0,0.0,0.0,0.0,0.5,0.5
58,0AUDLJ08S_00565.mp4,옆으로 펀치하기,덤벨,47,0.0,0.0,0.0,0.0,0.5,0.5
265,0AUDLJ08S_00264.mp4,의자 앞에서 앉았다 일어서기,의자,67,1.0,0.0,0.0,0.0,0.0,0.0
15,0AUDLJ08S_00520.mp4,의자 앞에서 앉았다 일어서기,의자,62,1.0,0.0,0.0,0.0,0.0,0.0
267,0AUDLJ08S_00266.mp4,의자에 앉아 다리 뻗어 올리기,의자|매트,59,1.0,0.0,0.0,0.0,0.0,0.0
18,0AUDLJ08S_00523.mp4,의자에 앉아 다리 뻗어 올리기,의자|매트,70,1.0,0.0,0.0,0.0,0.0,0.0
292,0AUDLJ08S_00316.mp4,점프 팔굽혀펴기,,45,0.0,0.0,0.0,0.0,0.5,0.5
68,0AUDLJ08S_00577.mp4,점프 팔굽혀펴기,,56,0.0,0.0,0.0,0.0,0.5,0.5
279,0AUDLJ08S_00288.mp4,짐볼에 엎드려서 팔 다리 들기,짐볼,52,1.0,0.0,0.0,0.0,0.0,0.0
44,0AUDLJ08S_00549.mp4,짐볼에 엎드려서 팔 다리 들기,짐볼,69,1.0,0.0,0.0,0.0,0.0,0.0
301,0AUDLJ08S_00346.mp4,탄력밴드 당기면서 팔 들어올리기,밴드,67,0.0,0.0,0.0,1.0,0.0,0.0
98,0AUDLJ08S_00622.mp4,탄력밴드 당기면서 팔 들어올리기,밴드,62,0.0,0.0,0.0,1.0,0.0,0.0
274,0AUDLJ08S_00278.mp4,탄력밴드 어깨 가쪽 돌림,밴드,63,1.0,0.0,0.0,0.0,0.0,0.0
46,0AUDLJ08S_00551.mp4,탄력밴드 어깨 가쪽 돌림,밴드,67,1.0,0.0,0.0,0.0,0.0,0.0
296,0AUDLJ08S_00337.mp4,테이블 이용하여 팔 옆으로 벌리기,테이블,55,0.0,0.0,0.0,1.0,0.0,0.0
87,0AUDLJ08S_00611.mp4,테이블 이용하여 팔 옆으로 벌리기,테이블,57,0.0,0.0,0.0,1.0,0.0,0.0
260,0AUDLJ08S_00253.mp4,팔꿈치 굽히기,물병|밴드,58,1.0,0.0,0.0,0.0,0.0,0.0
52,0AUDLJ08S_00559.mp4,팔꿈치 굽히기,물병|밴드,71,1.0,0.0,0.0,0.0,0.0,0.0
269,0AUDLJ08S_00270.mp4,한발 서서 균형잡기,의자,64,1.0,0.0,0.0,0.0,0.0,0.0
24,0AUDLJ08S_00529.mp4,한발 서서 균형잡기,의자,59,1.0,0.0,0.0,0.0,0.0,0.0

In [442]:
# 제목과 도구가 동일한 중복 영상에서는 영상 길이가 가장 짧은 하나만 남김

workout_videos = (
    workout_videos
    .sort_values("video_length")
    .drop_duplicates(
        subset=["title", "equipment"],
        keep="first"
    )
    .reset_index(drop=True)
)

print("최종 영상 수:", len(workout_videos))

remaining_duplicates = workout_videos.duplicated(
    subset=["title", "equipment"],
    keep=False
).sum()

print("제목+도구 중복 영상 수:", remaining_duplicates)

최종 영상 수: 275
제목+도구 중복 영상 수: 0

In [443]:
# 팔굽혀펴기 관련 영상들의 체력요인 정보를 비교하여 팔굽혀펴기-2의 라벨 이상 여부를 확인

pushup_check = workout_videos[
    workout_videos["title"].str.contains(
        "팔굽혀펴기",
        na=False
    )
][
    [
        "file_nm",
        "title",
        "strength",
        "muscularEndurance",
        "cardiovascularEndurance",
        "flexibility",
        "agility",
        "power",
        "equipment"
    ]
]

display(pushup_check)

,file_nm,title,strength,muscularEndurance,cardiovascularEndurance,flexibility,agility,power,equipment
4,0AUDLJ08S_00316.mp4,점프 팔굽혀펴기,0.0,0.0,0.0,0.0,0.5,0.5,
14,0AUDLJ08S_00602.mp4,팔굽혀펴기-2,0.0,0.0,0.0,1.0,0.0,0.0,매트
127,0AUDLJ08S_00849.mp4,좌우 이동하며 팔굽혀펴기,0.0,0.0,0.0,0.0,0.0,1.0,박스
153,0AUDLJ08S_00850.mp4,팔굽혀펴기 후 점프하기,0.0,0.0,0.0,0.0,0.0,1.0,박스
252,0AUDLJ08S_00873.mp4,팔굽혀펴기-3,0.5,0.5,0.0,0.0,0.0,0.0,매트
259,0AUDLJ08S_00874.mp4,뒤로 팔굽혀펴기-1,0.5,0.5,0.0,0.0,0.0,0.0,박스

In [444]:
# 체력요인이 유연성으로 잘못 분류된 팔굽혀펴기-2 영상을 추천 후보에서 제외

workout_videos = workout_videos[
    workout_videos["file_nm"] != "0AUDLJ08S_00602.mp4"
].reset_index(drop=True)

print("최종 영상 수:", len(workout_videos))
print(
    "팔굽혀펴기-2 잔존:",
    (workout_videos["file_nm"] == "0AUDLJ08S_00602.mp4").sum()
)

최종 영상 수: 274
팔굽혀펴기-2 잔존: 0

In [445]:
# 최종 추천 후보 데이터의 개수·결측치·중복·체력요인·URL을 종합 검증

print("=== 기본 정보 ===")
print("전체 영상 수:", len(workout_videos))
print("고유 file_nm:", workout_videos["file_nm"].nunique())
print("컬럼 수:", len(workout_videos.columns))

print("\n=== 결측치 ===")
print(workout_videos.isna().sum())

print("\n=== 중복 검사 ===")
print(
    "file_nm 중복:",
    workout_videos["file_nm"].duplicated().sum()
)
print(
    "title + equipment 중복:",
    workout_videos.duplicated(
        subset=["title", "equipment"]
    ).sum()
)

print("\n=== 체력요인 검사 ===")
factor_sum = workout_videos[factor_cols].sum(axis=1)

print(
    "체력요인 합 = 1:",
    factor_sum.round(10).eq(1.0).sum()
)
print(
    "체력요인 합 != 1:",
    (~factor_sum.round(10).eq(1.0)).sum()
)

print("\n=== 체력요인별 영상 수 ===")
print(
    (workout_videos[factor_cols] > 0)
    .sum()
    .sort_values(ascending=False)
)

print("\n=== URL 검사 ===")
print(
    "URL 없음:",
    workout_videos["file_url"].isna().sum()
)
print(
    "빈 URL:",
    workout_videos["file_url"].fillna("").str.strip().eq("").sum()
)
print(
    "mp4로 끝나지 않는 URL:",
    (~workout_videos["file_url"].fillna("").str.endswith(".mp4")).sum()
)

=== 기본 정보 ===
전체 영상 수: 274
고유 file_nm: 274
컬럼 수: 12

=== 결측치 ===
file_nm                    0
title                      0
file_url                   0
video_length               0
age_group                  0
strength                   0
muscularEndurance          0
cardiovascularEndurance    0
flexibility                0
agility                    0
power                      0
equipment                  0
dtype: int64

=== 중복 검사 ===
file_nm 중복: 0
title + equipment 중복: 0

=== 체력요인 검사 ===
체력요인 합 = 1: 274
체력요인 합 != 1: 0

=== 체력요인별 영상 수 ===
strength                   117
flexibility                110
muscularEndurance           35
power                       34
agility                     23
cardiovascularEndurance      3
dtype: int64

=== URL 검사 ===
URL 없음: 0
빈 URL: 0
mp4로 끝나지 않는 URL: 0

In [446]:
# 바벨이 필요한 영상을 최종 추천 후보에서 제외

workout_videos = workout_videos[
    ~workout_videos["equipment"]
    .str.split("|")
    .apply(lambda tools: "바벨" in tools)
].reset_index(drop=True)

print("최종 영상 수:", len(workout_videos))
print(
    "바벨 포함 영상 잔존:",
    workout_videos["equipment"]
    .str.split("|")
    .apply(lambda tools: "바벨" in tools)
    .sum()
)

최종 영상 수: 273
바벨 포함 영상 잔존: 0

In [447]:
# 최종 영상의 체력요인 가중치 유효성과 요인별 영상 수만 다시 확인

factor_sum = workout_videos[factor_cols].sum(axis=1)

print("체력요인 합 = 1:", factor_sum.round(10).eq(1.0).sum())
print("체력요인 합 != 1:", (~factor_sum.round(10).eq(1.0)).sum())

print("\n체력요인별 영상 수:")
print(
    (workout_videos[factor_cols] > 0)
    .sum()
    .sort_values(ascending=False)
)

# 실내 짧은 운동 미션에 적합하지 않은 일반 달리기 영상을 추천 후보에서 제외

workout_videos = workout_videos[
    workout_videos["file_nm"] != "0AUDLJ08S_00460.mp4"
].reset_index(drop=True)

print("최종 영상 수:", len(workout_videos))
print(
    "달리기 영상 잔존:",
    (workout_videos["file_nm"] == "0AUDLJ08S_00460.mp4").sum()
)

체력요인 합 = 1: 273
체력요인 합 != 1: 0

체력요인별 영상 수:
strength                   116
flexibility                110
muscularEndurance           35
power                       34
agility                     23
cardiovascularEndurance      3
dtype: int64
최종 영상 수: 272
달리기 영상 잔존: 0

In [448]:
# 최종 검증을 통과한 272개 운동 영상을 v2 CSV와 JSON 파일로 저장

workout_videos.to_csv(
    PROCESSED_DIR / "workout_videos_v2.csv",
    index=False,
    encoding="utf-8-sig"
)

workout_videos.to_json(
    PROCESSED_DIR / "workout_videos_v2.json",
    orient="records",
    force_ascii=False,
    indent=2
)

print("CSV 저장:", PROCESSED_DIR / "workout_videos_v2.csv")
print("JSON 저장:", PROCESSED_DIR / "workout_videos_v2.json")
print("최종 영상 수:", len(workout_videos))

CSV 저장: data/processed/workout_videos_v2.csv
JSON 저장: data/processed/workout_videos_v2.json
최종 영상 수: 272

In [449]:
# 최종 운동 영상 CSV의 URL을 이용해 모든 영상을 로컬 폴더에 다운로드
import pandas as pd
import requests
from pathlib import Path

csv_path = Path("data/processed/workout_videos_v2.csv")
download_dir = Path("data/videos")

download_dir.mkdir(parents=True, exist_ok=True)

df = pd.read_csv(csv_path)

for i, row in df.iterrows():
    file_nm = row["file_nm"]
    url = row["file_url"]
    save_path = download_dir / file_nm

    if save_path.exists():
        print(f"[{i+1}/{len(df)}] 이미 존재: {file_nm}")
        continue

    try:
        with requests.get(url, stream=True, timeout=60) as response:
            response.raise_for_status()

            with open(save_path, "wb") as f:
                for chunk in response.iter_content(chunk_size=1024 * 1024):
                    if chunk:
                        f.write(chunk)

        print(f"[{i+1}/{len(df)}] 완료: {file_nm}")

    except Exception as e:
        print(f"[{i+1}/{len(df)}] 실패: {file_nm} / {e}")

[1/272] 이미 존재: 0AUDLJ08S_00311.mp4
[2/272] 이미 존재: 0AUDLJ08S_00237.mp4
[3/272] 이미 존재: 0AUDLJ08S_00830.mp4
[4/272] 이미 존재: 0AUDLJ08S_00287.mp4
[5/272] 이미 존재: 0AUDLJ08S_00316.mp4
[6/272] 이미 존재: 0AUDLJ08S_00573.mp4
[7/272] 이미 존재: 0AUDLJ08S_00302.mp4
[8/272] 이미 존재: 0AUDLJ08S_00315.mp4
[9/272] 이미 존재: 0AUDLJ08S_00565.mp4
[10/272] 이미 존재: 0AUDLJ08S_00273.mp4
[11/272] 이미 존재: 0AUDLJ08S_00312.mp4
[12/272] 이미 존재: 0AUDLJ08S_00252.mp4
[13/272] 이미 존재: 0AUDLJ08S_00575.mp4
[14/272] 이미 존재: 0AUDLJ08S_00275.mp4
[15/272] 이미 존재: 0AUDLJ08S_00838.mp4
[16/272] 이미 존재: 0AUDLJ08S_00307.mp4
[17/272] 이미 존재: 0AUDLJ08S_00238.mp4
[18/272] 이미 존재: 0AUDLJ08S_00516.mp4
[19/272] 이미 존재: 0AUDLJ08S_00288.mp4
[20/272] 이미 존재: 0AUDLJ08S_00291.mp4
[21/272] 이미 존재: 0AUDLJ08S_00506.mp4
[22/272] 이미 존재: 0AUDLJ08S_00566.mp4
[23/272] 이미 존재: 0AUDLJ08S_00842.mp4
[24/272] 이미 존재: 0AUDLJ08S_00572.mp4
[25/272] 이미 존재: 0AUDLJ08S_00509.mp4
[26/272] 이미 존재: 0AUDLJ08S_00831.mp4
[27/272] 이미 존재: 0AUDLJ08S_00568.mp4
[28/272] 이미 존재: 0AUDLJ08S_00337.mp4
[29/272] 이미 존재: 0AUDLJ08S_00815.mp4
[30/272] 이미 존재: 0AUDLJ08S_00570.mp4
[31/272] 이미 존재: 0AUDLJ08S_00569.mp4
[32/272] 이미 존재: 0AUDLJ08S_00242.mp4
[33/272] 이미 존재: 0AUDLJ08S_00255.mp4
[34/272] 이미 존재: 0AUDLJ08S_00844.mp4
[35/272] 이미 존재: 0AUDLJ08S_00829.mp4
[36/272] 이미 존재: 0AUDLJ08S_00567.mp4
[37/272] 이미 존재: 0AUDLJ08S_00522.mp4
[38/272] 이미 존재: 0AUDLJ08S_00834.mp4
[39/272] 이미 존재: 0AUDLJ08S_00528.mp4
[40/272] 이미 존재: 0AUDLJ08S_00608.mp4
[41/272] 이미 존재: 0AUDLJ08S_00303.mp4
[42/272] 이미 존재: 0AUDLJ08S_00609.mp4
[43/272] 이미 존재: 0AUDLJ08S_00613.mp4
[44/272] 이미 존재: 0AUDLJ08S_00292.mp4
[45/272] 이미 존재: 0AUDLJ08S_00612.mp4
[46/272] 이미 존재: 0AUDLJ08S_00618.mp4
[47/272] 이미 존재: 0AUDLJ08S_00617.mp4
[48/272] 이미 존재: 0AUDLJ08S_00616.mp4
[49/272] 이미 존재: 0AUDLJ08S_00614.mp4
[50/272] 이미 존재: 0AUDLJ08S_00548.mp4
[51/272] 이미 존재: 0AUDLJ08S_00615.mp4
[52/272] 이미 존재: 0AUDLJ08S_00619.mp4
[53/272] 이미 존재: 0AUDLJ08S_00265.mp4
[54/272] 이미 존재: 0AUDLJ08S_00621.mp4
[55/272] 이미 존재: 0AUDLJ08S_00253.mp4
[56/272] 이미 존재: 0AUDLJ08S_00810.mp4
[57/272] 이미 존재: 0AUDLJ08S_00239.mp4
[58/272] 이미 존재: 0AUDLJ08S_00828.mp4
[59/272] 이미 존재: 0AUDLJ08S_00236.mp4
[60/272] 이미 존재: 0AUDLJ08S_00620.mp4
[61/272] 이미 존재: 0AUDLJ08S_00811.mp4
[62/272] 이미 존재: 0AUDLJ08S_00254.mp4
[63/272] 이미 존재: 0AUDLJ08S_00266.mp4
[64/272] 이미 존재: 0AUDLJ08S_00267.mp4
[65/272] 이미 존재: 0AUDLJ08S_00529.mp4
[66/272] 이미 존재: 0AUDLJ08S_00837.mp4
[67/272] 이미 존재: 0AUDLJ08S_00812.mp4
[68/272] 이미 존재: 0AUDLJ08S_00603.mp4
[69/272] 이미 존재: 0AUDLJ08S_00843.mp4
[70/272] 이미 존재: 0AUDLJ08S_00623.mp4
[71/272] 이미 존재: 0AUDLJ08S_00839.mp4
[72/272] 이미 존재: 0AUDLJ08S_00624.mp4
[73/272] 이미 존재: 0AUDLJ08S_00525.mp4
[74/272] 이미 존재: 0AUDLJ08S_00832.mp4
[75/272] 이미 존재: 0AUDLJ08S_00840.mp4
[76/272] 이미 존재: 0AUDLJ08S_00622.mp4
[77/272] 이미 존재: 0AUDLJ08S_00520.mp4
[78/272] 이미 존재: 0AUDLJ08S_00817.mp4
[79/272] 이미 존재: 0AUDLJ08S_00247.mp4
[80/272] 이미 존재: 0AUDLJ08S_00278.mp4
[81/272] 이미 존재: 0AUDLJ08S_00966.mp4
[82/272] 이미 존재: 0AUDLJ08S_00233.mp4
[83/272] 이미 존재: 0AUDLJ08S_00998.mp4
[84/272] 이미 존재: 0AUDLJ08S_00540.mp4
[85/272] 이미 존재: 0AUDLJ08S_00607.mp4
[86/272] 이미 존재: 0AUDLJ08S_00606.mp4
[87/272] 이미 존재: 0AUDLJ08S_00583.mp4
[88/272] 이미 존재: 0AUDLJ08S_00561.mp4
[89/272] 이미 존재: 0AUDLJ08S_00284.mp4
[90/272] 이미 존재: 0AUDLJ08S_00544.mp4
[91/272] 이미 존재: 0AUDLJ08S_00271.mp4
[92/272] 이미 존재: 0AUDLJ08S_00336.mp4
[93/272] 이미 존재: 0AUDLJ08S_00560.mp4
[94/272] 이미 존재: 0AUDLJ08S_00518.mp4
[95/272] 이미 존재: 0AUDLJ08S_00251.mp4
[96/272] 이미 존재: 0AUDLJ08S_00464.mp4
[97/272] 이미 존재: 0AUDLJ08S_00500.mp4
[98/272] 이미 존재: 0AUDLJ08S_00243.mp4
[99/272] 이미 존재: 0AUDLJ08S_00808.mp4
[100/272] 이미 존재: 0AUDLJ08S_00286.mp4
[101/272] 이미 존재: 0AUDLJ08S_00531.mp4
[102/272] 이미 존재: 0AUDLJ08S_00542.mp4
[103/272] 이미 존재: 0AUDLJ08S_00524.mp4
[104/272] 이미 존재: 0AUDLJ08S_00276.mp4
[105/272] 이미 존재: 0AUDLJ08S_00298.mp4
[106/272] 이미 존재: 0AUDLJ08S_00545.mp4
[107/272] 이미 존재: 0AUDLJ08S_00512.mp4
[108/272] 이미 존재: 0AUDLJ08S_00503.mp4
[109/272] 이미 존재: 0AUDLJ08S_00283.mp4
[110/272] 이미 존재: 0AUDLJ08S_00240.mp4
[111/272] 이미 존재: 0AUDLJ08S_00519.mp4
[112/272] 이미 존재: 0AUDLJ08S_00521.mp4
[113/272] 이미 존재: 0AUDLJ08S_00605.mp4
[114/272] 이미 존재: 0AUDLJ08S_00539.mp4
[115/272] 이미 존재: 0AUDLJ08S_00553.mp4
[116/272] 이미 존재: 0AUDLJ08S_00554.mp4
[117/272] 이미 존재: 0AUDLJ08S_00965.mp4
[118/272] 이미 존재: 0AUDLJ08S_00511.mp4
[119/272] 이미 존재: 0AUDLJ08S_00550.mp4
[120/272] 이미 존재: 0AUDLJ08S_00546.mp4
[121/272] 이미 존재: 0AUDLJ08S_00526.mp4
[122/272] 이미 존재: 0AUDLJ08S_00846.mp4
[123/272] 이미 존재: 0AUDLJ08S_00588.mp4
[124/272] 이미 존재: 0AUDLJ08S_00816.mp4
[125/272] 이미 존재: 0AUDLJ08S_00849.mp4
[126/272] 이미 존재: 0AUDLJ08S_00534.mp4
[127/272] 이미 존재: 0AUDLJ08S_00533.mp4
[128/272] 이미 존재: 0AUDLJ08S_00514.mp4
[129/272] 이미 존재: 0AUDLJ08S_00538.mp4
[130/272] 이미 존재: 0AUDLJ08S_00814.mp4
[131/272] 이미 존재: 0AUDLJ08S_00835.mp4
[132/272] 이미 존재: 0AUDLJ08S_00813.mp4
[133/272] 이미 존재: 0AUDLJ08S_00996.mp4
[134/272] 이미 존재: 0AUDLJ08S_00245.mp4
[135/272] 이미 존재: 0AUDLJ08S_00809.mp4
[136/272] 이미 존재: 0AUDLJ08S_00584.mp4
[137/272] 이미 존재: 0AUDLJ08S_00878.mp4
[138/272] 이미 존재: 0AUDLJ08S_00847.mp4
[139/272] 이미 존재: 0AUDLJ08S_00527.mp4
[140/272] 이미 존재: 0AUDLJ08S_00582.mp4
[141/272] 이미 존재: 0AUDLJ08S_00972.mp4
[142/272] 이미 존재: 0AUDLJ08S_00587.mp4
[143/272] 이미 존재: 0AUDLJ08S_00959.mp4
[144/272] 이미 존재: 0AUDLJ08S_00557.mp4
[145/272] 이미 존재: 0AUDLJ08S_00589.mp4
[146/272] 이미 존재: 0AUDLJ08S_00836.mp4
[147/272] 이미 존재: 0AUDLJ08S_00891.mp4
[148/272] 이미 존재: 0AUDLJ08S_00535.mp4
[149/272] 이미 존재: 0AUDLJ08S_00964.mp4
[150/272] 이미 존재: 0AUDLJ08S_00976.mp4
[151/272] 이미 존재: 0AUDLJ08S_00850.mp4
[152/272] 이미 존재: 0AUDLJ08S_00903.mp4
[153/272] 이미 존재: 0AUDLJ08S_00909.mp4
[154/272] 이미 존재: 0AUDLJ08S_00968.mp4
[155/272] 이미 존재: 0AUDLJ08S_00967.mp4
[156/272] 이미 존재: 0AUDLJ08S_00986.mp4
[157/272] 이미 존재: 0AUDLJ08S_00349.mp4
[158/272] 이미 존재: 0AUDLJ08S_00913.mp4
[159/272] 이미 존재: 0AUDLJ08S_00924.mp4
[160/272] 이미 존재: 0AUDLJ08S_00590.mp4
[161/272] 이미 존재: 0AUDLJ08S_00231.mp4
[162/272] 이미 존재: 0AUDLJ08S_00887.mp4
[163/272] 이미 존재: 0AUDLJ08S_00988.mp4
[164/272] 이미 존재: 0AUDLJ08S_00305.mp4
[165/272] 이미 존재: 0AUDLJ08S_00256.mp4
[166/272] 이미 존재: 0AUDLJ08S_00562.mp4
[167/272] 이미 존재: 0AUDLJ08S_00530.mp4
[168/272] 이미 존재: 0AUDLJ08S_00978.mp4
[169/272] 이미 존재: 0AUDLJ08S_00552.mp4
[170/272] 이미 존재: 0AUDLJ08S_00979.mp4
[171/272] 이미 존재: 0AUDLJ08S_00963.mp4
[172/272] 이미 존재: 0AUDLJ08S_00883.mp4
[173/272] 이미 존재: 0AUDLJ08S_00989.mp4
[174/272] 이미 존재: 0AUDLJ08S_00914.mp4
[175/272] 이미 존재: 0AUDLJ08S_00983.mp4
[176/272] 이미 존재: 0AUDLJ08S_00908.mp4
[177/272] 이미 존재: 0AUDLJ08S_00977.mp4
[178/272] 이미 존재: 0AUDLJ08S_00970.mp4
[179/272] 이미 존재: 0AUDLJ08S_00532.mp4
[180/272] 이미 존재: 0AUDLJ08S_00990.mp4
[181/272] 이미 존재: 0AUDLJ08S_00971.mp4
[182/272] 이미 존재: 0AUDLJ08S_00919.mp4
[183/272] 이미 존재: 0AUDLJ08S_00961.mp4
[184/272] 이미 존재: 0AUDLJ08S_00962.mp4
[185/272] 이미 존재: 0AUDLJ08S_00888.mp4
[186/272] 이미 존재: 0AUDLJ08S_00918.mp4
[187/272] 이미 존재: 0AUDLJ08S_00854.mp4
[188/272] 이미 존재: 0AUDLJ08S_00257.mp4
[189/272] 이미 존재: 0AUDLJ08S_00921.mp4
[190/272] 이미 존재: 0AUDLJ08S_00585.mp4
[191/272] 이미 존재: 0AUDLJ08S_00993.mp4
[192/272] 이미 존재: 0AUDLJ08S_00904.mp4
[193/272] 이미 존재: 0AUDLJ08S_00987.mp4
[194/272] 이미 존재: 0AUDLJ08S_00982.mp4
[195/272] 이미 존재: 0AUDLJ08S_00992.mp4
[196/272] 이미 존재: 0AUDLJ08S_00727.mp4
[197/272] 이미 존재: 0AUDLJ08S_00932.mp4
[198/272] 이미 존재: 0AUDLJ08S_00591.mp4
[199/272] 이미 존재: 0AUDLJ08S_00995.mp4
[200/272] 이미 존재: 0AUDLJ08S_00886.mp4
[201/272] 이미 존재: 0AUDLJ08S_00937.mp4
[202/272] 이미 존재: 0AUDLJ08S_00875.mp4
[203/272] 이미 존재: 0AUDLJ08S_00944.mp4
[204/272] 이미 존재: 0AUDLJ08S_00877.mp4
[205/272] 이미 존재: 0AUDLJ08S_00885.mp4
[206/272] 이미 존재: 0AUDLJ08S_00969.mp4
[207/272] 이미 존재: 0AUDLJ08S_00994.mp4
[208/272] 이미 존재: 0AUDLJ08S_00892.mp4
[209/272] 이미 존재: 0AUDLJ08S_00906.mp4
[210/272] 이미 존재: 0AUDLJ08S_00925.mp4
[211/272] 이미 존재: 0AUDLJ08S_00960.mp4
[212/272] 이미 존재: 0AUDLJ08S_00991.mp4
[213/272] 이미 존재: 0AUDLJ08S_00897.mp4
[214/272] 이미 존재: 0AUDLJ08S_00882.mp4
[215/272] 이미 존재: 0AUDLJ08S_00876.mp4
[216/272] 이미 존재: 0AUDLJ08S_00581.mp4
[217/272] 이미 존재: 0AUDLJ08S_00586.mp4
[218/272] 이미 존재: 0AUDLJ08S_00845.mp4
[219/272] 이미 존재: 0AUDLJ08S_00900.mp4
[220/272] 이미 존재: 0AUDLJ08S_00984.mp4
[221/272] 이미 존재: 0AUDLJ08S_00647.mp4
[222/272] 이미 존재: 0AUDLJ08S_00973.mp4
[223/272] 이미 존재: 0AUDLJ08S_00917.mp4
[224/272] 이미 존재: 0AUDLJ08S_00943.mp4
[225/272] 이미 존재: 0AUDLJ08S_00915.mp4
[226/272] 이미 존재: 0AUDLJ08S_00731.mp4
[227/272] 이미 존재: 0AUDLJ08S_00910.mp4
[228/272] 이미 존재: 0AUDLJ08S_00890.mp4
[229/272] 이미 존재: 0AUDLJ08S_00997.mp4
[230/272] 이미 존재: 0AUDLJ08S_00933.mp4
[231/272] 이미 존재: 0AUDLJ08S_00929.mp4
[232/272] 이미 존재: 0AUDLJ08S_00881.mp4
[233/272] 이미 존재: 0AUDLJ08S_00920.mp4
[234/272] 이미 존재: 0AUDLJ08S_00922.mp4
[235/272] 이미 존재: 0AUDLJ08S_00930.mp4
[236/272] 이미 존재: 0AUDLJ08S_00724.mp4
[237/272] 이미 존재: 0AUDLJ08S_00733.mp4
[238/272] 이미 존재: 0AUDLJ08S_00726.mp4
[239/272] 이미 존재: 0AUDLJ08S_00905.mp4
[240/272] 이미 존재: 0AUDLJ08S_00732.mp4
[241/272] 이미 존재: 0AUDLJ08S_00985.mp4
[242/272] 이미 존재: 0AUDLJ08S_00931.mp4
[243/272] 이미 존재: 0AUDLJ08S_00974.mp4
[244/272] 이미 존재: 0AUDLJ08S_00935.mp4
[245/272] 이미 존재: 0AUDLJ08S_00911.mp4
[246/272] 이미 존재: 0AUDLJ08S_00923.mp4
[247/272] 이미 존재: 0AUDLJ08S_00848.mp4
[248/272] 이미 존재: 0AUDLJ08S_00939.mp4
[249/272] 이미 존재: 0AUDLJ08S_00884.mp4
[250/272] 이미 존재: 0AUDLJ08S_00873.mp4
[251/272] 이미 존재: 0AUDLJ08S_00926.mp4
[252/272] 이미 존재: 0AUDLJ08S_00938.mp4
[253/272] 이미 존재: 0AUDLJ08S_00729.mp4
[254/272] 이미 존재: 0AUDLJ08S_00980.mp4
[255/272] 이미 존재: 0AUDLJ08S_00940.mp4
[256/272] 이미 존재: 0AUDLJ08S_00928.mp4
[257/272] 이미 존재: 0AUDLJ08S_00874.mp4
[258/272] 이미 존재: 0AUDLJ08S_00981.mp4
[259/272] 이미 존재: 0AUDLJ08S_00294.mp4
[260/272] 이미 존재: 0AUDLJ08S_00941.mp4
[261/272] 이미 존재: 0AUDLJ08S_00942.mp4
[262/272] 이미 존재: 0AUDLJ08S_00889.mp4
[263/272] 이미 존재: 0AUDLJ08S_00916.mp4
[264/272] 이미 존재: 0AUDLJ08S_00725.mp4
[265/272] 이미 존재: 0AUDLJ08S_00936.mp4
[266/272] 이미 존재: 0AUDLJ08S_00927.mp4
[267/272] 이미 존재: 0AUDLJ08S_00880.mp4
[268/272] 이미 존재: 0AUDLJ08S_00728.mp4
[269/272] 이미 존재: 0AUDLJ08S_00879.mp4
[270/272] 이미 존재: 0AUDLJ08S_00723.mp4
[271/272] 이미 존재: 0AUDLJ08S_00975.mp4
[272/272] 이미 존재: 0AUDLJ08S_00934.mp4